# Generated by Django 5.1.5 on 2025-02-19 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sws', '0026_customerintentionproject_is_planned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalCertificateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_homologation_certificate', models.BooleanField(default=False)),
                ('certificate_type', models.CharField(max_length=50)),
                ('sale_certificate', models.CharField(max_length=50)),
                ('road_certificate', models.CharField(max_length=50)),
                ('temporary_vehicle_registration', models.CharField(max_length=50)),
                ('permanenet_vehicle_registration', models.CharField(max_length=50)),
                ('internation_certification', models.CharField(max_length=50)),
                ('inhouse_registartion', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'approval_certificate_info',
            },
        ),
        migrations.CreateModel(
            name='TaxRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professinal_tax_registration', models.BooleanField(default=False)),
                ('gst_registration', models.CharField(max_length=50)),
                ('shop_registration', models.CharField(max_length=50)),
                ('factory_license', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'approval_tax_registration',
            },
        ),
        migrations.CreateModel(
            name='LicenseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_license_contract', models.BooleanField(default=False)),
                ('is_migrate_contract', models.BooleanField(default=False)),
                ('is_bocw_contract', models.BooleanField(default=False)),
                ('is_contract_labour', models.BooleanField(default=False)),
                ('is_boiler_registration', models.BooleanField(default=False)),
                ('is_labour_registration', models.BooleanField(default=False)),
                ('is_exporter', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building_plan_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sws.sector')),
            ],
            options={
                'db_table': 'approval_license_contract',
            },
        ),
        migrations.CreateModel(
            name='ServiceExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sector', models.CharField(max_length=30)),
                ('line_of_business', models.CharField(default='', max_length=20)),
                ('industry_scale', models.CharField(default='', max_length=20)),
                ('investment_amount', models.FloatField(default='', max_length=20)),
                ('land_needed', models.BooleanField(default=False)),
                ('land_applicability', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('change_land_use', models.CharField(max_length=50)),
                ('change_land_applicability', models.CharField(max_length=50)),
                ('land_mutation', models.CharField(max_length=50)),
                ('land_mutation_applicability', models.CharField(max_length=50)),
                ('temporary_service_connection', models.CharField(max_length=50)),
                ('water_connection', models.CharField(max_length=50)),
                ('permanent_service_connection', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sws.sector')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_service_exemption',
            },
        ),
        migrations.CreateModel(
            name='CommonApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_property_registration', models.BooleanField(default=False)),
                ('tree_felling_noc', models.BooleanField(default=False)),
                ('tree_felling_applicability', models.CharField(default='', max_length=20)),
                ('tree_transit_noc', models.BooleanField(default=False)),
                ('tree_transit_applicability', models.BooleanField(default=False)),
                ('land_applicability', models.CharField(max_length=50)),
                ('fire_noc', models.CharField(max_length=50)),
                ('factory_plan', models.CharField(max_length=50)),
                ('is_road_cutting_permission', models.BooleanField(default=False)),
                ('estabilish_consent', models.CharField(max_length=50)),
                ('operate_consent', models.CharField(max_length=50)),
                ('is_electric_installation', models.BooleanField(default=False)),
                ('is_inspection_approval', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_exemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval.serviceexemption')),
            ],
            options={
                'db_table': 'common_approval',
            },
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sws.sector')),
            ],
        ),
    ]
