# Generated by Django 5.1.5 on 2025-02-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0001_initial"),
        ("sws", "0029_industrialarealist_authority"),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_tag", models.CharField(default="", max_length=255)),
                ("expected_output", models.CharField(default="", max_length=255)),
            ],
            options={
                "db_table": "master_eligibility_criteria",
            },
        ),
        migrations.CreateModel(
            name="ApprovalList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("act_name", models.CharField(default="", max_length=255)),
                ("phase", models.CharField(default="", max_length=40)),
                ("is_exemption", models.BooleanField(default=False)),
                ("is_common", models.BooleanField(default=False)),
                ("is_service", models.BooleanField(default=False)),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department",
                        to="sws.departmentlist",
                    ),
                ),
            ],
            options={
                "db_table": "master_approval_lists",
            },
        ),
        migrations.CreateModel(
            name="ApprovalCriteriaMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_criteria",
                        to="approval.approvallist",
                    ),
                ),
                (
                    "questions",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_criteria",
                        to="approval.eligibilitycriteria",
                    ),
                ),
            ],
            options={
                "db_table": "master_criteria_approval_mappings",
            },
        ),
        migrations.CreateModel(
            name="IAExemptionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_ia_clearance",
                        to="approval.approvallist",
                    ),
                ),
                (
                    "industrial_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industrial_area_list_clearance",
                        to="sws.industrialarealist",
                    ),
                ),
            ],
            options={
                "db_table": "master_industryarea_exemption_mappings",
            },
        ),
        migrations.CreateModel(
            name="SectorClearanceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_clearance",
                        to="approval.approvallist",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_clearance",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "master_sector_clearance_mappings",
            },
        ),
        migrations.CreateModel(
            name="SectorServiceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_service",
                        to="approval.approvallist",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_service",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "master_sector_service_mappings",
            },
        ),
        migrations.CreateModel(
            name="SubSectorClearanceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_sub_clearance",
                        to="approval.approvallist",
                    ),
                ),
                (
                    "subsector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsector_clearance",
                        to="approval.subsector",
                    ),
                ),
            ],
            options={
                "db_table": "master_subsector_clearance_mappings",
            },
        ),
    ]
