# Generated by Django 5.1.5 on 2025-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0002_eligibilitycriteria_approvallist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approvallist",
            name="act_name",
        ),
        migrations.AddField(
            model_name="approvallist",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
