# Generated by Django 5.1.5 on 2025-02-20 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0003_remove_approvallist_act_name_and_more"),
        ("sws", "0030_alter_customerintentionproject_investment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsectorclearancemapping",
            name="subsector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsector_clearance",
                to="sws.subsector",
            ),
        ),
    ]
