# Generated by Django 5.1.5 on 2025-02-21 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0004_alter_subsectorclearancemapping_subsector"),
        ("sws", "0030_alter_customerintentionproject_investment_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCAFService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "department_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phase", models.CharField(blank=True, max_length=40, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caf_approvals",
                        to="approval.approvallist",
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caf_services",
                        to="sws.caf",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "caf_user_services",
            },
        ),
    ]
