# Generated by Django 5.1.5 on 2025-03-08 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0005_usercafservice"),
        ("sws", "0032_customerintentionproject_intention_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="KYAQuestionBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_tag",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        blank=True,
                        help_text="Values are dropdown, radio, combobox etc",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "kya_question_bank",
            },
        ),
        migrations.CreateModel(
            name="KYAQuestionBankOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_value",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "option_display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="approval.kyaquestionbank",
                    ),
                ),
            ],
            options={
                "db_table": "kya_question_bank_options",
            },
        ),
        migrations.CreateModel(
            name="SectorApprovalMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[("mandatory", "Mandatory"), ("optional", "Optional")],
                        default="optional",
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=9999)),
            ],
            options={
                "db_table": "kya_sector_clearance_mappings",
            },
        ),
        migrations.CreateModel(
            name="SectorQuestionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_tag",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "question_output",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "kya_sector_question_approvals",
            },
        ),
        migrations.CreateModel(
            name="SectorQuestionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("mandatory", "Mandatory"),
                            ("mandatory_question", "Mandatory Questions"),
                            ("optional", "Optional"),
                            ("service", "Service"),
                        ],
                        default="optional",
                        max_length=40,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("static", "Static"), ("dynamic", "Dynamic")],
                        default="dynamic",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "In-Active"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("next_question_tag", models.CharField(default="", max_length=100)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sqm_questions",
                        to="approval.kyaquestionbank",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sqm_sector",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "kya_sector_question_mappings",
            },
        ),
        migrations.CreateModel(
            name="SectorQuestionMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=100, null=True)),
                ("target", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sector_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sqmethod_questions",
                        to="approval.sectorquestionmapping",
                    ),
                ),
            ],
            options={
                "db_table": "kya_sector_question_methods",
            },
        ),
        migrations.CreateModel(
            name="SectorQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.IntegerField(default=9999)),
                ("next_question_tag", models.CharField(default="", max_length=100)),
                (
                    "question_options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_question_options",
                        to="approval.kyaquestionbankoption",
                    ),
                ),
                (
                    "sector_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_questions",
                        to="approval.sectorquestionmapping",
                    ),
                ),
            ],
            options={
                "db_table": "kya_sector_question_options",
            },
        ),
        migrations.CreateModel(
            name="SubSectorApprovalMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[("mandatory", "Mandatory"), ("optional", "Optional")],
                        default="optional",
                        max_length=20,
                    ),
                ),
                ("display_order", models.IntegerField(default=9999)),
            ],
            options={
                "db_table": "kya_subsector_clearance_mappings",
            },
        ),
        migrations.CreateModel(
            name="SubSectorQuestionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_tag",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "question_output",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "kya_subsector_question_approvals",
            },
        ),
        migrations.CreateModel(
            name="SubSectorQuestionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("mandatory_clearance", "Mandatory Clearance"),
                            ("optional_clearance", "Optional Clearance"),
                        ],
                        default="optional_clearance",
                        max_length=40,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("static", "Static"), ("dynamic", "Dynamic")],
                        default="dynamic",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "In-Active"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("next_question_tag", models.CharField(default="", max_length=100)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssqm_questions",
                        to="approval.kyaquestionbank",
                    ),
                ),
                (
                    "subsector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssqm_subsector",
                        to="sws.subsector",
                    ),
                ),
            ],
            options={
                "db_table": "kya_subsector_question_mappings",
            },
        ),
        migrations.CreateModel(
            name="SubSectorQuestionMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=100, null=True)),
                ("target", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "subsector_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssqmethod_questions",
                        to="approval.subsectorquestionmapping",
                    ),
                ),
            ],
            options={
                "db_table": "kya_subsector_question_methods",
            },
        ),
        migrations.CreateModel(
            name="SubSectorQuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.IntegerField(default=9999)),
                ("next_question_tag", models.CharField(default="", max_length=100)),
                (
                    "question_options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssqo_options",
                        to="approval.kyaquestionbankoption",
                    ),
                ),
                (
                    "subsector_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssqo_questions",
                        to="approval.subsectorquestionmapping",
                    ),
                ),
            ],
            options={
                "db_table": "kya_subsector_question_options",
            },
        ),
        migrations.DeleteModel(
            name="ApprovalCertificateInfo",
        ),
        migrations.RemoveField(
            model_name="approvalcriteriamapping",
            name="approval",
        ),
        migrations.RemoveField(
            model_name="approvalcriteriamapping",
            name="questions",
        ),
        migrations.RemoveField(
            model_name="commonapproval",
            name="service_exemption",
        ),
        migrations.RemoveField(
            model_name="licensecontract",
            name="building_plan_approval",
        ),
        migrations.RemoveField(
            model_name="sectorclearancemapping",
            name="approval",
        ),
        migrations.RemoveField(
            model_name="sectorclearancemapping",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="sectorservicemapping",
            name="approval",
        ),
        migrations.RemoveField(
            model_name="sectorservicemapping",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="serviceexemption",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="serviceexemption",
            name="user",
        ),
        migrations.RemoveField(
            model_name="subsector",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="subsectorclearancemapping",
            name="approval",
        ),
        migrations.RemoveField(
            model_name="subsectorclearancemapping",
            name="subsector",
        ),
        migrations.DeleteModel(
            name="TaxRegistration",
        ),
        migrations.RemoveField(
            model_name="approvallist",
            name="is_common",
        ),
        migrations.RemoveField(
            model_name="approvallist",
            name="is_exemption",
        ),
        migrations.RemoveField(
            model_name="approvallist",
            name="is_service",
        ),
        migrations.AddField(
            model_name="approvallist",
            name="approval_type",
            field=models.CharField(
                choices=[("service", "Services"), ("clearance", "Clearance")],
                default="clearance",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="approvallist",
            table="kya_approval_lists",
        ),
        migrations.AlterModelTable(
            name="iaexemptionmapping",
            table="kya_industryarea_exemption_mappings",
        ),
        migrations.AddField(
            model_name="sectorapprovalmapping",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_clearance",
                to="approval.approvallist",
            ),
        ),
        migrations.AddField(
            model_name="sectorapprovalmapping",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sector_clearance",
                to="sws.sector",
            ),
        ),
        migrations.AddField(
            model_name="sectorquestionapproval",
            name="approval",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sqam_approvals",
                to="approval.approvallist",
            ),
        ),
        migrations.AddField(
            model_name="sectorquestionapproval",
            name="sector_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sqam_questions",
                to="approval.sectorquestionmapping",
            ),
        ),
        migrations.AddField(
            model_name="subsectorapprovalmapping",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_sub_clearance",
                to="approval.approvallist",
            ),
        ),
        migrations.AddField(
            model_name="subsectorapprovalmapping",
            name="subsector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsector_clearance",
                to="sws.subsector",
            ),
        ),
        migrations.AddField(
            model_name="subsectorquestionapproval",
            name="approval",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ssqm_approvals",
                to="approval.approvallist",
            ),
        ),
        migrations.AddField(
            model_name="subsectorquestionapproval",
            name="subsector_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ssqm_questions",
                to="approval.subsectorquestionmapping",
            ),
        ),
        migrations.DeleteModel(
            name="ApprovalCriteriaMapping",
        ),
        migrations.DeleteModel(
            name="EligibilityCriteria",
        ),
        migrations.DeleteModel(
            name="CommonApproval",
        ),
        migrations.DeleteModel(
            name="LicenseContract",
        ),
        migrations.DeleteModel(
            name="SectorClearanceMapping",
        ),
        migrations.DeleteModel(
            name="SectorServiceMapping",
        ),
        migrations.DeleteModel(
            name="ServiceExemption",
        ),
        migrations.DeleteModel(
            name="SubSector",
        ),
        migrations.DeleteModel(
            name="SubSectorClearanceMapping",
        ),
    ]
