# Generated by Django 5.1.5 on 2025-03-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0006_kyaquestionbank_kyaquestionbankoption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectorquestionmapping",
            name="approval_type",
            field=models.CharField(
                choices=[
                    ("mandatory", "Mandatory"),
                    ("mandatory_question", "Mandatory Questions"),
                    ("optional", "Optional"),
                    ("service", "Service"),
                    ("service_question", "Service Questions"),
                ],
                default="optional",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="subsectorquestionmapping",
            name="approval_type",
            field=models.CharField(
                choices=[
                    ("mandatory", "Mandatory"),
                    ("mandatory_question", "Mandatory Question"),
                    ("optional", "Optional"),
                ],
                default="optional",
                max_length=100,
            ),
        ),
    ]
