# Generated by Django 5.1.5 on 2025-03-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0007_alter_sectorquestionmapping_approval_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvallist",
            name="timelines",
            field=models.CharField(default="", max_length=40),
        ),
    ]
