# Generated by Django 5.1.5 on 2025-03-10 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0008_approvallist_timelines"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kyaquestionbankoption",
            name="question",
        ),
    ]
