# Generated by Django 5.1.5 on 2025-03-12 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0009_remove_kyaquestionbankoption_question"),
        ("sws", "0037_departmentlist_code_delete_cafmanufacturingdetails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="approvallist",
            name="department",
        ),
        migrations.CreateModel(
            name="ApprovalDepartmentList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criteria", models.CharField(default="", max_length=100)),
                ("status", models.BooleanField(default=True)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adl_approval",
                        to="approval.approvallist",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adl_department",
                        to="sws.departmentlist",
                    ),
                ),
            ],
            options={
                "db_table": "kya_approval_departments",
            },
        ),
    ]
