# Generated by Django 5.1.5 on 2025-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0011_userapprovals_userapprovalitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectorquestionmapping",
            name="display_order",
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name="subsectorquestionmapping",
            name="display_order",
            field=models.IntegerField(default=9999),
        ),
    ]
