# Generated by Django 5.1.5 on 2025-03-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0012_sectorquestionmapping_display_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercafservice",
            name="department_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
