# Generated by Django 5.1.5 on 2025-04-01 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0013_alter_usercafservice_department_name"),
        ("sws", "0045_remove_lineofactivity_business_industry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorCriteriaHideApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criteria", models.CharField(max_length=100)),
                ("output", models.CharField(max_length=100)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_hide",
                        to="approval.approvallist",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_hide_approvals",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "kya_sector_criteria_hide_approvals",
            },
        ),
    ]
