# Generated by Django 5.1.5 on 2025-04-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0014_sectorcriteriahideapproval"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvallist",
            name="instruction",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
