# Generated by Django 5.1.5 on 2025-08-19 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0015_approvallist_instruction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalConfigurationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redirect_url", models.TextField(blank=True, null=True)),
                (
                    "request_method",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_configs",
                        to="approval.approvallist",
                    ),
                ),
            ],
            options={
                "db_table": "kya_service_configs",
            },
        ),
    ]
