# Generated by Django 5.1.5 on 2025-08-22 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0016_approvalconfigurationmodel"),
        ("sws", "0068_serviceconfigmodel_servicedynamicfieldmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercafservice",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_user_service",
                to="sws.departmentlist",
            ),
        ),
        migrations.AddField(
            model_name="usercafservice",
            name="request_json",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usercafservice",
            name="request_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
