# Generated by Django 5.1.5 on 2025-08-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0017_usercafservice_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalconfigurationmodel",
            name="request_params",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
