# Generated by Django 5.1.5 on 2025-08-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0018_approvalconfigurationmodel_request_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalconfigurationmodel",
            name="signing_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
