# Generated by Django 5.1.5 on 2025-02-11 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organization_type",
            },
        ),
        migrations.CreateModel(
            name="OrganizationAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("pin_code", models.CharField(max_length=6)),
                ("state", models.CharField(max_length=255)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("Registered", "Registered Office"),
                            ("Communication", "Communication"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_organization_address",
            },
        ),
        migrations.CreateModel(
            name="UserOrgazination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("registered_under_msme", models.BooleanField(default=False)),
                (
                    "msme_registration_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("firm_registration_number", models.CharField(max_length=255)),
                ("registration_date", models.DateField()),
                (
                    "scale_of_industry",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("firm_pan_number", models.CharField(max_length=10)),
                ("firm_gstin_number", models.CharField(max_length=15)),
                ("website_url", models.URLField()),
                ("helpdesk_number", models.CharField(max_length=15)),
                ("firm_email_id", models.EmailField(max_length=254)),
                (
                    "organization_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.organizationtype",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_organization",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("mobile_number", models.CharField(max_length=15)),
                ("email_id", models.EmailField(max_length=254)),
                ("aadhaar_number", models.CharField(max_length=12)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("Director", "Director"),
                            ("Manager", "Manager"),
                            ("Partner", "Partner"),
                            ("Proprietor", "Proprietor"),
                            ("Authorized", "Authorized"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_contact_detail",
            },
        ),
    ]
