# Generated by Django 5.1.5 on 2025-02-12 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationaddress",
            name="user_profile",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_profile",
        ),
        migrations.AddField(
            model_name="organizationaddress",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_address",
                to="userprofile.userorgazination",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_users_profile",
                to="userprofile.userorgazination",
            ),
        ),
    ]
