# Generated by Django 5.1.5 on 2025-02-14 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0018_userwishlist"),
        ("userprofile", "0002_remove_organizationaddress_user_profile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserKnowYourClearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("total_investment", models.CharField(max_length=255)),
                ("firm_size", models.CharField(max_length=255)),
                ("anticipated_turnover", models.CharField(max_length=255)),
                (
                    "pollution_requirement",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                (
                    "export_oriented_unit",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                ("investor_type", models.CharField(default="", max_length=40)),
                ("land_category", models.CharField(default="", max_length=100)),
                ("land_type", models.CharField(default="", max_length=100)),
                (
                    "building_height",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                ("water_source", models.CharField(default="", max_length=255)),
                ("power_requirement", models.CharField(default="", max_length=255)),
                (
                    "need_temp_connection",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                (
                    "power_limit_exceed",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                ("proposed_employment", models.CharField(default="", max_length=30)),
                ("no_of_state_employer", models.CharField(default="", max_length=30)),
                (
                    "no_of_contractual_employer",
                    models.CharField(default="", max_length=30),
                ),
                (
                    "need_building_works",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                (
                    "is_employees_exceeds_salary_limit",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                (
                    "business_location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_business_location",
                        to="sws.district",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_district",
                        to="sws.district",
                    ),
                ),
                (
                    "existing_sector_in_mp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_sectors_in_mp",
                        to="sws.sector",
                    ),
                ),
                (
                    "operation_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_activities",
                        to="sws.activity",
                    ),
                ),
                (
                    "organization_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_org_type",
                        to="userprofile.organizationtype",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_sectors",
                        to="sws.sector",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_investment_kyc",
            },
        ),
    ]
