# Generated by Django 5.1.5 on 2025-02-16 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_userknowyourclearance"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationaddress",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="organizationaddress",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userorgazination",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userorgazination",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="organizationaddress",
            name="address_line",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="organizationaddress",
            name="address_type",
            field=models.CharField(
                choices=[
                    ("Registered", "Registered Office"),
                    ("Communication", "Communication"),
                ],
                default="Registered",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organizationaddress",
            name="city",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="organizationaddress",
            name="district",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="organizationaddress",
            name="pin_code",
            field=models.CharField(default="", max_length=6),
        ),
        migrations.AlterField(
            model_name="organizationaddress",
            name="state",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userorgazination",
            name="firm_email_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userorgazination",
            name="firm_gstin_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="userorgazination",
            name="firm_pan_number",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="userorgazination",
            name="firm_registration_number",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userorgazination",
            name="helpdesk_number",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="userorgazination",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userorgazination",
            name="website_url",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="aadhaar_number",
            field=models.CharField(default="", max_length=12),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("Director", "Director"),
                    ("Manager", "Manager"),
                    ("Partner", "Partner"),
                    ("Proprietor", "Proprietor"),
                    ("Authorized", "Authorized"),
                ],
                default="Authorized",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="designation",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mobile_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
