# Generated by Django 5.1.5 on 2025-02-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0019_alter_plotdetails_district"),
        ("userprofile", "0004_organizationaddress_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationaddress",
            name="city",
        ),
        migrations.AlterField(
            model_name="organizationaddress",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_address_district",
                to="sws.sector",
            ),
        ),
        migrations.AlterField(
            model_name="organizationaddress",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_address_state",
                to="sws.state",
            ),
        ),
    ]
