# Generated by Django 5.1.5 on 2025-02-17 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0019_alter_plotdetails_district"),
        ("userprofile", "0005_remove_organizationaddress_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationaddress",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_address_district",
                to="sws.district",
            ),
        ),
    ]
