# Generated by Django 5.1.5 on 2025-02-18 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0006_alter_organizationaddress_district"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bank_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "account_holder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bank_ifsc_code",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=18, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blocked", "blocked"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_bank_details",
            },
        ),
    ]
