# Generated by Django 5.1.5 on 2025-02-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0007_userbankdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbankdetails",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("inactive", "inactive"),
                    ("blocked", "blocked"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
