# Generated by Django 5.1.5 on 2025-02-19 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0008_alter_userbankdetails_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "application_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "department_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("in-process", "In-process"),
                            ("objection", "Objection"),
                        ],
                        default="in-process",
                        max_length=10,
                    ),
                ),
                ("pan_no", models.CharField(default="", max_length=10)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "service_tracker",
            },
        ),
    ]
