# Generated by Django 5.1.5 on 2025-03-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0010_userprofilepdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="aadhaar_number",
        ),
    ]
