# Generated by Django 5.1.5 on 2025-03-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0011_remove_userprofile_aadhaar_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserKnowYourClearance",
        ),
    ]
