# Generated by Django 5.1.5 on 2025-04-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0013_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilepdf",
            name="doc_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userprofilepdf",
            name="user_pdf_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
