# Generated by Django 5.1.5 on 2025-04-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0014_alter_userprofilepdf_doc_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExceptionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=255)),
                ("error_message", models.TextField()),
                ("stack_trace", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "exception_logs",
            },
        ),
    ]
