# Generated by Django 5.1.5 on 2025-05-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0015_exceptionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorgazination",
            name="date_of_incorporation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userorgazination",
            name="pan_verify",
            field=models.BooleanField(default=False),
        ),
    ]
