# Generated by Django 5.1.5 on 2025-05-11 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0016_userorgazination_date_of_incorporation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("mobile_number", models.CharField(default="", max_length=15)),
                ("email_id", models.CharField(default="", max_length=100)),
                (
                    "contact_type",
                    models.CharField(blank=True, default="", max_length=40, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_users",
                        to="userprofile.userorgazination",
                    ),
                ),
            ],
            options={
                "db_table": "organization_user_contact_detail",
            },
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
