# Generated by Django 5.1.5 on 2025-05-12 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0031_customuserprofile_dob_customuserprofile_father_name_and_more",
        ),
        ("userprofile", "0017_organizationusermodel_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationusermodel",
            name="country_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.country",
            ),
        ),
    ]
