# Generated by Django 5.1.5 on 2025-07-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0018_organizationusermodel_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationusermodel",
            name="designation",
            field=models.CharField(
                blank=True, default="Managing Director", max_length=255, null=True
            ),
        ),
    ]
