# Generated by Django 5.1.5 on 2025-07-27 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0063_districtblocklist_block_priority"),
        ("userprofile", "0019_organizationusermodel_designation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationusermodel",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.designation",
            ),
        ),
    ]
