# Generated by Django 5.1.5 on 2025-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0021_alter_organizationusermodel_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationusermodel",
            name="other_designation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
