# Generated by Django 5.1.5 on 2025-02-06 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0009_alter_customuserprofile_mobile_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveCalculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yop", models.IntegerField()),
                (
                    "industry_type",
                    models.CharField(
                        choices=[("food", "Food"), ("gen", "General")], max_length=50
                    ),
                ),
                ("investment", models.CharField(max_length=50)),
                ("ppyp", models.CharField(max_length=50)),
                ("cyp", models.CharField(max_length=50)),
                ("export_per", models.CharField(max_length=50)),
                ("bipa", models.CharField(max_length=50)),
                ("ybipa", models.CharField(max_length=50)),
                ("gsvm", models.CharField(max_length=50)),
                ("export_multiple", models.CharField(max_length=50)),
                ("employement_multiple", models.CharField(max_length=50)),
                ("ayia", models.CharField(max_length=50)),
                ("total_employer", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.customuserprofile",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_calculator",
            },
        ),
    ]
