# Generated by Django 5.1.5 on 2025-02-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incentivecalculator",
            name="ayia",
        ),
        migrations.RemoveField(
            model_name="incentivecalculator",
            name="industry_type",
        ),
        migrations.RemoveField(
            model_name="incentivecalculator",
            name="ppyp",
        ),
        migrations.RemoveField(
            model_name="incentivecalculator",
            name="ybipa",
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="fdi_multiple",
            field=models.CharField(default="1", max_length=50),
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="fdi_per",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="geo_multiple",
            field=models.CharField(default="1", max_length=50),
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="is_back_area_company",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="is_cement_company",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="is_company_exports",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="is_company_received_fdi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="sector_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="ssm",
            field=models.CharField(default="1", max_length=50),
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="subsidy_amount",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AddField(
            model_name="incentivecalculator",
            name="yuc",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="incentivecalculator",
            name="bipa",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="incentivecalculator",
            name="cyp",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="incentivecalculator",
            name="employement_multiple",
            field=models.CharField(default="1", max_length=50),
        ),
        migrations.AlterField(
            model_name="incentivecalculator",
            name="export_multiple",
            field=models.CharField(default="1", max_length=50),
        ),
        migrations.AlterField(
            model_name="incentivecalculator",
            name="export_per",
            field=models.CharField(default="0", max_length=50),
        ),
        migrations.AlterField(
            model_name="incentivecalculator",
            name="gsvm",
            field=models.CharField(default="1", max_length=50),
        ),
        migrations.AlterField(
            model_name="incentivecalculator",
            name="investment",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="incentivecalculator",
            name="total_employer",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="incentivecalculator",
            name="yop",
            field=models.IntegerField(default=1),
        ),
    ]
