# Generated by Django 5.1.5 on 2025-04-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incentive",
            "0003_incentivecaf_incafproject_incafpower_incafinvestment_and_more",
        ),
        ("sws", "0047_measurementunitlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Document Name", max_length=100)),
            ],
            options={
                "db_table": "document_list",
            },
        ),
        migrations.AddField(
            model_name="incentivecaf",
            name="acknowledgement",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incentivecaf",
            name="acknowledgement_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="caf",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incaf_investment",
                to="incentive.incentivecaf",
            ),
        ),
        migrations.AlterField(
            model_name="incafpower",
            name="additional_load",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Additional Load consumption",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafpower",
            name="caf",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incaf_power",
                to="incentive.incentivecaf",
            ),
        ),
        migrations.AlterField(
            model_name="incafpower",
            name="existing_load",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Existing Load consumption",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafpower",
            name="load_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Load consumption",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InCAFDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_path",
                    models.CharField(
                        blank=True,
                        help_text="is_ipp true then first incentive year needed",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_documents",
                        to="incentive.incentivecaf",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_documents",
                        to="incentive.documentlist",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_caf_documents_details",
            },
        ),
        migrations.CreateModel(
            name="InCAFEmployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employees_from_mp",
                    models.IntegerField(help_text="Employees from MP"),
                ),
                (
                    "employees_outside_mp",
                    models.IntegerField(help_text="Employees Outside From MP"),
                ),
                ("total_employee", models.IntegerField(help_text="Total Employee")),
                (
                    "caf",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_employment",
                        to="incentive.incentivecaf",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_caf_employement_details",
            },
        ),
        migrations.CreateModel(
            name="InCAFIncentive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_ipp", models.BooleanField(default=False)),
                ("is_gia", models.BooleanField(default=False)),
                ("is_mandifee", models.BooleanField(default=False)),
                (
                    "comm_proudction_date",
                    models.DateField(
                        blank=True, help_text="is_ipp true then cpd needed", null=True
                    ),
                ),
                (
                    "first_purchase_date",
                    models.DateField(
                        blank=True,
                        help_text="is_ipp true then first purchased needed",
                        null=True,
                    ),
                ),
                (
                    "first_sale_date",
                    models.DateField(
                        blank=True,
                        help_text="is_ipp true then first sale needed",
                        null=True,
                    ),
                ),
                (
                    "incentive_year",
                    models.CharField(
                        blank=True,
                        help_text="is_ipp true then first incentive year needed",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "type_of_wms",
                    models.CharField(
                        blank=True,
                        help_text="is_gia true then wms needed",
                        max_length=75,
                        null=True,
                    ),
                ),
                (
                    "wms_total_expenditure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="is_gia true then wms expenditure needed",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "mandi_license",
                    models.CharField(
                        blank=True,
                        help_text="is_mandiifee true then license needed",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "mandi_license_date",
                    models.DateField(
                        blank=True,
                        help_text="is_mandiifee true then license date needed",
                        null=True,
                    ),
                ),
                (
                    "caf",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_incentive",
                        to="incentive.incentivecaf",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_caf_incentive_details",
            },
        ),
        migrations.CreateModel(
            name="InCAFPowerLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplementary_load",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Supplementary Saction load",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "supplementary_load_date",
                    models.DateField(
                        blank=True,
                        help_text="Supplementary Saction load date",
                        null=True,
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_power_load",
                        to="incentive.incentivecaf",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_caf_power_load_details",
            },
        ),
        migrations.CreateModel(
            name="InCAFProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_name",
                    models.CharField(help_text="Product Name", max_length=255),
                ),
                (
                    "total_annual_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual Capacity",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_products",
                        to="incentive.incentivecaf",
                    ),
                ),
                (
                    "measurement_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_measurement",
                        to="sws.measurementunitlist",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_caf_product_details",
            },
        ),
        migrations.CreateModel(
            name="InCAFSubMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meter_number",
                    models.CharField(help_text="Sub meter details", max_length=100),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_submeter",
                        to="incentive.incentivecaf",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_caf_submeter_details",
            },
        ),
    ]
