# Generated by Django 5.1.5 on 2025-04-05 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0004_documentlist_incentivecaf_acknowledgement_and_more"),
        ("sws", "0047_measurementunitlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incafdocuments",
            name="document_name",
            field=models.CharField(
                default="", help_text="document name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="incafproduct",
            name="measurement_unit_name",
            field=models.CharField(
                blank=True,
                help_text="Measurement unit names",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incentivecaf",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incafproduct",
            name="measurement_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incaf_measurement",
                to="sws.measurementunitlist",
            ),
        ),
        migrations.CreateModel(
            name="IncentiveActivityHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incentive_approving",
                    models.CharField(
                        help_text="forward or raise query", max_length=100
                    ),
                ),
                (
                    "approving_document",
                    models.CharField(
                        blank=True,
                        help_text="document uploaded",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("approving_comment", models.TextField(blank=True, null=True)),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, help_text="approver name", max_length=200, null=True
                    ),
                ),
                (
                    "approver_designation",
                    models.CharField(
                        blank=True,
                        help_text="approver designation",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_activity",
                        to="incentive.incentivecaf",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_activity_history",
            },
        ),
    ]
