# Generated by Django 5.1.5 on 2025-04-05 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0005_incafdocuments_document_name_and_more"),
        ("sws", "0047_measurementunitlist"),
        ("userprofile", "0012_delete_userknowyourclearance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incentiveactivityhistory",
            name="activity_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="incentiveactivityhistory",
            name="caf_status",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="incentiveactivityhistory",
            name="ip_address",
            field=models.CharField(
                blank=True, help_text="ip address", max_length=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="incentiveactivityhistory",
            name="status_remark",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="incentivecaf",
            name="caf_pdf_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="URL of PDF",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incentivecaf",
            name="current_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caf_approver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_activity",
                to="sws.activity",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block_district",
                to="sws.districtblocklist",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="constitution_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_type_id",
                to="userprofile.organizationtype",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_district",
                to="sws.district",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="industrial_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="in_industrial_area",
                to="sws.industrialarealist",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="line_of_activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_line_of_activity",
                to="sws.lineofactivity",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="regional_office",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_regional",
                to="sws.regionaloffice",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_sector",
                to="sws.sector",
            ),
        ),
        migrations.AlterField(
            model_name="incentivecaf",
            name="status",
            field=models.CharField(
                default="In-Progress",
                help_text="In-Progress, Completed, Deleted",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="incentivecaf",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caf_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="IncentiveAgenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        help_text="Pending for creation or created", max_length=50
                    ),
                ),
                (
                    "created_user_name",
                    models.CharField(
                        help_text="name of user created the agenda", max_length=100
                    ),
                ),
                (
                    "unit_name",
                    models.CharField(
                        default="", help_text="Company Name", max_length=255
                    ),
                ),
                (
                    "constitution_type_name",
                    models.CharField(
                        default="", help_text="Constitution Type Name", max_length=100
                    ),
                ),
                (
                    "gstin_and_date",
                    models.CharField(
                        default="", help_text="GSTIN & Date", max_length=255
                    ),
                ),
                (
                    "iem_a_number",
                    models.CharField(
                        default="", help_text="IEM Part A Number", max_length=100
                    ),
                ),
                ("iem_a_date", models.DateField(help_text="IEM Part A Date")),
                (
                    "iem_b_number",
                    models.CharField(
                        default="", help_text="IEM Part B Number", max_length=100
                    ),
                ),
                ("iem_b_date", models.DateField(help_text="IEM Part B Date")),
                (
                    "block_name",
                    models.CharField(
                        default="", help_text="Block names", max_length=75
                    ),
                ),
                ("address_of_unit", models.TextField(help_text="Address of Unit")),
                (
                    "category_of_block",
                    models.CharField(
                        default="", help_text="Priority or Non Priority", max_length=15
                    ),
                ),
                (
                    "activity_name",
                    models.CharField(
                        default="", help_text="activity name", max_length=50
                    ),
                ),
                (
                    "sector_name",
                    models.CharField(
                        default="", help_text="Sector name", max_length=200
                    ),
                ),
                (
                    "line_of_activity_name",
                    models.CharField(
                        default="", help_text="Line of Activity name", max_length=200
                    ),
                ),
                (
                    "application_filling_date",
                    models.DateField(help_text="Application Filling Date"),
                ),
                (
                    "first_production_year",
                    models.CharField(
                        default="", help_text="First product year", max_length=10
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(default="", help_text="unit_type", max_length=60),
                ),
                (
                    "comm_production_date",
                    models.DateField(help_text="Commercial Production Date"),
                ),
                (
                    "ht_contract_demand",
                    models.CharField(
                        default="", help_text="11KV, 33KV etc", max_length=15
                    ),
                ),
                (
                    "saction_power_load",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="decimal values",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "investment_in_plant_machinery",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "eligible_investment_plant_machinery",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bipa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "yearly_bipa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "ipp",
                    models.CharField(default="", help_text="IPP name", max_length=200),
                ),
                (
                    "eligible_period",
                    models.CharField(
                        default="",
                        help_text="Eligible Period of Assitance",
                        max_length=200,
                    ),
                ),
                ("employee_of_mp", models.IntegerField(blank=True, null=True)),
                ("employee_outside_mp", models.IntegerField(blank=True, null=True)),
                ("total_employee", models.IntegerField(blank=True, null=True)),
                (
                    "percentage_in_employee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fact_about_case", models.TextField(blank=True, null=True)),
                ("recommendation", models.TextField(blank=True, null=True)),
                ("slec_proposal", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_activity",
                        to="sws.activity",
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_agenda",
                        to="incentive.incentivecaf",
                    ),
                ),
                (
                    "constitution_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agendat_org_type_id",
                        to="userprofile.organizationtype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_agenda_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line_of_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_line_of_activity",
                        to="sws.lineofactivity",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_sector",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_agenda",
            },
        ),
        migrations.CreateModel(
            name="IncentiveAgendaProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measurement_unit_name",
                    models.CharField(
                        blank=True,
                        help_text="Measurement unit names",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, help_text="Product Name", max_length=255, null=True
                    ),
                ),
                (
                    "total_annual_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual Capacity",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "comm_production_date",
                    models.DateField(
                        blank=True, help_text="Commercial Production Date", null=True
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_product",
                        to="incentive.incentiveagenda",
                    ),
                ),
                (
                    "measurement_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_measurement",
                        to="sws.measurementunitlist",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_agenda_products",
            },
        ),
    ]
