# Generated by Django 5.1.5 on 2025-04-06 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0006_incentiveactivityhistory_activity_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveCafNumberGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caf_number", models.CharField(max_length=30, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "incentive_caf_number_generator",
            },
        ),
        migrations.RenameField(
            model_name="incentiveactivityhistory",
            old_name="approved_by",
            new_name="user_name",
        ),
        migrations.RenameField(
            model_name="incentiveactivityhistory",
            old_name="approver_designation",
            new_name="user_role",
        ),
        migrations.RemoveField(
            model_name="incentiveactivityhistory",
            name="approving_comment",
        ),
        migrations.RemoveField(
            model_name="incentiveactivityhistory",
            name="approving_document",
        ),
        migrations.RemoveField(
            model_name="incentiveactivityhistory",
            name="incentive_approving",
        ),
        migrations.AddField(
            model_name="incentiveactivityhistory",
            name="activity_result",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="agenda_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="incentivecaf",
            name="incentive_caf_number",
            field=models.CharField(
                blank=True, default="", help_text="caf number", max_length=30, null=True
            ),
        ),
        migrations.AlterField(
            model_name="documentlist",
            name="name",
            field=models.CharField(help_text="Document Name", max_length=150),
        ),
        migrations.AlterField(
            model_name="incafdocuments",
            name="document_name",
            field=models.CharField(
                default="", help_text="document name", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="incafdocuments",
            name="document_path",
            field=models.CharField(
                blank=True,
                help_text="is_ipp true then first incentive year needed",
                max_length=200,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="IncentiveApprovalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incentive_approving",
                    models.CharField(
                        help_text="forward or raise query", max_length=100
                    ),
                ),
                (
                    "current_approver_designation",
                    models.CharField(help_text="GM, CGM etc", max_length=200),
                ),
                (
                    "approving_document",
                    models.CharField(
                        blank=True,
                        help_text="document uploaded",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("approving_remark", models.TextField(blank=True, null=True)),
                (
                    "name_of_authority",
                    models.CharField(
                        blank=True, help_text="user name", max_length=200, null=True
                    ),
                ),
                (
                    "authority_designation",
                    models.CharField(
                        blank=True,
                        help_text="approver designation",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_approval",
                        to="incentive.incentivecaf",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_approval_history",
            },
        ),
        migrations.CreateModel(
            name="IncentiveAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("module", models.CharField(help_text="module_name", max_length=100)),
                (
                    "user_name",
                    models.CharField(
                        blank=True, help_text="user name", max_length=200, null=True
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        blank=True, help_text="user role", max_length=200, null=True
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True, help_text="form field", max_length=200, null=True
                    ),
                ),
                (
                    "old_value",
                    models.CharField(blank=True, help_text="old_value", null=True),
                ),
                (
                    "new_value",
                    models.CharField(blank=True, help_text="new_value", null=True),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_audit",
                        to="incentive.incentivecaf",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_audit_logs",
            },
        ),
    ]
