# Generated by Django 5.1.5 on 2025-04-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0007_incentivecafnumbergenerator_and_more"),
        ("sws", "0047_measurementunitlist"),
        ("userprofile", "0012_delete_userknowyourclearance"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveSlecOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unit_name",
                    models.CharField(
                        default="", help_text="Company Name", max_length=255
                    ),
                ),
                (
                    "constitution_type_name",
                    models.CharField(
                        default="", help_text="Constitution Type Name", max_length=100
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(default="", help_text="unit_type", max_length=60),
                ),
                (
                    "activity_name",
                    models.CharField(
                        default="", help_text="activity name", max_length=50
                    ),
                ),
                (
                    "sector_name",
                    models.CharField(
                        default="", help_text="Sector name", max_length=200
                    ),
                ),
                (
                    "line_of_activity_name",
                    models.CharField(
                        default="", help_text="Line of Activity name", max_length=200
                    ),
                ),
                (
                    "category_of_block",
                    models.CharField(
                        default="", help_text="Priority or Non Priority", max_length=15
                    ),
                ),
                (
                    "date_of_slec_meeting",
                    models.DateField(help_text="Date of Slec meeting"),
                ),
                (
                    "slec_meeting_number",
                    models.CharField(help_text="Slec meeting number", max_length=100),
                ),
                (
                    "eligible_investment_plant_machinery",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "bipa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "yearly_bipa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("eligibility_from", models.DateField(help_text="elegibility from")),
                ("eligibility_to", models.DateField(help_text="elegibility to")),
                ("remark", models.TextField(blank=True, help_text="Remark", null=True)),
                (
                    "name_of_authority",
                    models.CharField(
                        blank=True, help_text="user name", max_length=200, null=True
                    ),
                ),
                (
                    "authority_designation",
                    models.CharField(
                        blank=True,
                        help_text="approver designation",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="slec order pending",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slec_activity",
                        to="sws.activity",
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_slec_order",
                        to="incentive.incentivecaf",
                    ),
                ),
                (
                    "constitution_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slec_order_org_id",
                        to="userprofile.organizationtype",
                    ),
                ),
                (
                    "line_of_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slec_line_of_activity",
                        to="sws.lineofactivity",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slec_sector",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_slec_order",
            },
        ),
        migrations.CreateModel(
            name="IncentiveSlecProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measurement_unit_name",
                    models.CharField(
                        blank=True,
                        help_text="Measurement unit names",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, help_text="Product Name", max_length=255, null=True
                    ),
                ),
                (
                    "total_annual_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual Capacity",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "comm_production_date",
                    models.DateField(
                        blank=True, help_text="Commercial Production Date", null=True
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slec_product",
                        to="incentive.incentiveagenda",
                    ),
                ),
                (
                    "measurement_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slec_measurement",
                        to="sws.measurementunitlist",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_slec_products",
            },
        ),
        migrations.CreateModel(
            name="IncentiveSlecYealy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incentive_year",
                    models.CharField(
                        blank=True, help_text="incentive year", max_length=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Paid and Unpaid",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "claim_year_serial_number",
                    models.CharField(
                        blank=True, help_text="1,2,3", max_length=4, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Incentive",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, help_text="Remarks", max_length=255, null=True
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slec_yearly_incentive",
                        to="incentive.incentiveagenda",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_slec_year",
            },
        ),
    ]
