# Generated by Django 5.1.5 on 2025-04-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0008_incentiveslecorder_incentiveslecproduct_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incentivecaf",
            name="current_approver",
        ),
        migrations.AlterField(
            model_name="incentiveapprovalhistory",
            name="authority_designation",
            field=models.CharField(
                blank=True, help_text="approver role", max_length=200, null=True
            ),
        ),
    ]
