# Generated by Django 5.1.5 on 2025-04-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0009_remove_incentivecaf_current_approver_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incentiveapprovalhistory",
            old_name="incentive_approving",
            new_name="incentive_action",
        ),
        migrations.RenameField(
            model_name="incentiveapprovalhistory",
            old_name="current_approver_designation",
            new_name="next_approver_designation",
        ),
    ]
