# Generated by Django 5.1.5 on 2025-04-14 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incentive",
            "0010_rename_incentive_approving_incentiveapprovalhistory_incentive_action_and_more",
        ),
        ("sws", "0047_measurementunitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentlist",
            name="digi_doc_type",
            field=models.CharField(
                blank=True, help_text="Document Type", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="documentlist",
            name="entity_doc_type",
            field=models.CharField(
                blank=True, help_text="Document Type", max_length=50, null=True
            ),
        ),
        migrations.CreateModel(
            name="SectorDocumentList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_type",
                    models.CharField(
                        default="Common", help_text="Common, GIA etc", max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="active",
                        help_text="active or inactive etc",
                        max_length=10,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_sector_specific_documents",
                        to="incentive.documentlist",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doc_sector",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_document_sector_list",
            },
        ),
    ]
