# Generated by Django 5.1.5 on 2025-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0011_documentlist_digi_doc_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentlist",
            name="name",
            field=models.TextField(help_text="Document Name"),
        ),
    ]
