# Generated by Django 5.1.5 on 2025-04-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0012_alter_documentlist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafproject",
            name="industrial_area_name",
            field=models.CharField(
                blank=True, default="", help_text="industrial area name", max_length=255
            ),
        ),
    ]
