# Generated by Django 5.1.5 on 2025-04-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0013_incafproject_industrial_area_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentlist",
            name="gstin_doc_type",
            field=models.CharField(
                blank=True, help_text="GSTIN Doc Type", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="documentlist",
            name="pan_doc_type",
            field=models.CharField(
                blank=True, help_text="Pan Doc type", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="documentlist",
            name="title",
            field=models.TextField(blank=True, help_text="Title Name", null=True),
        ),
        migrations.AlterField(
            model_name="documentlist",
            name="digi_doc_type",
            field=models.CharField(
                blank=True, help_text="Digi doc Type", max_length=50, null=True
            ),
        ),
    ]
