# Generated by Django 5.1.5 on 2025-04-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0014_documentlist_gstin_doc_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentlist",
            name="template_file_path",
            field=models.TextField(
                blank=True, help_text="Template file path", null=True
            ),
        ),
    ]
