# Generated by Django 5.1.5 on 2025-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0015_documentlist_template_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentiveapprovalhistory",
            name="is_overdue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incentiveapprovalhistory",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incentiveapprovalhistory",
            name="sla_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name="incentiveapprovalhistory",
            name="sla_due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
