# Generated by Django 5.1.5 on 2025-04-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_remove_workflowlist_next_flow_type_and_more"),
        ("incentive", "0016_incentiveapprovalhistory_is_overdue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentivecaf",
            name="current_approver_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caf_current_role",
                to="authentication.role",
            ),
        ),
        migrations.AddField(
            model_name="incentivecaf",
            name="sla_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incentivecaf",
            name="sla_due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
