# Generated by Django 5.1.5 on 2025-04-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0017_incentivecaf_current_approver_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentlist",
            name="gstin_doc_type",
        ),
        migrations.RemoveField(
            model_name="documentlist",
            name="pan_doc_type",
        ),
        migrations.AddField(
            model_name="documentlist",
            name="file_type",
            field=models.CharField(
                blank=True,
                help_text="Type of document upload",
                max_length=100,
                null=True,
            ),
        ),
    ]
