# Generated by Django 5.1.5 on 2025-04-19 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0018_remove_documentlist_gstin_doc_type_and_more"),
        ("sws", "0047_measurementunitlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incafproject",
            name="line_of_activity",
        ),
        migrations.RemoveField(
            model_name="incafproject",
            name="line_of_activity_name",
        ),
        migrations.RemoveField(
            model_name="incentiveagenda",
            name="line_of_activity",
        ),
        migrations.RemoveField(
            model_name="incentiveagenda",
            name="line_of_activity_name",
        ),
        migrations.RemoveField(
            model_name="incentiveslecorder",
            name="line_of_activity",
        ),
        migrations.RemoveField(
            model_name="incentiveslecorder",
            name="line_of_activity_name",
        ),
        migrations.AddField(
            model_name="incafproject",
            name="sub_sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_sub_sector",
                to="sws.subsector",
            ),
        ),
        migrations.AddField(
            model_name="incafproject",
            name="sub_sector_name",
            field=models.CharField(
                default="", help_text="Sub Sector name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="sub_sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agenda_sub_sector",
                to="sws.subsector",
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="sub_sector_name",
            field=models.CharField(
                default="", help_text="SubSector name", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="incentiveslecorder",
            name="sub_sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_sub_sector",
                to="sws.subsector",
            ),
        ),
        migrations.AddField(
            model_name="incentiveslecorder",
            name="sub_sector_name",
            field=models.CharField(
                default="", help_text="Sub Sector name", max_length=200
            ),
        ),
    ]
