# Generated by Django 5.1.5 on 2025-04-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0019_remove_incafproject_line_of_activity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incafproject",
            name="comm_production_date",
        ),
        migrations.RemoveField(
            model_name="incafproject",
            name="investment_in_plant_machinery",
        ),
        migrations.RemoveField(
            model_name="incafproject",
            name="total_investment_amount",
        ),
    ]
