# Generated by Django 5.1.5 on 2025-04-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0030_alter_customuserprofile_document_folder"),
        ("incentive", "0020_remove_incafproject_comm_production_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafproject",
            name="country_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.country",
            ),
        ),
    ]
