# Generated by Django 5.1.5 on 2025-04-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0021_incafproject_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafproject",
            name="country_code_name",
            field=models.CharField(
                blank=True, default="", help_text="Code value", max_length=15
            ),
        ),
    ]
