# Generated by Django 5.1.5 on 2025-04-23 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0022_incafproject_country_code_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incentiveslecproduct",
            name="caf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_product",
                to="incentive.incentivecaf",
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecyealy",
            name="caf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_yearly_incentive",
                to="incentive.incentivecaf",
            ),
        ),
    ]
