# Generated by Django 5.1.5 on 2025-04-23 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0023_alter_incentiveslecproduct_caf_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incentiveagendaproduct",
            name="caf",
        ),
        migrations.RemoveField(
            model_name="incentiveslecproduct",
            name="caf",
        ),
        migrations.RemoveField(
            model_name="incentiveslecyealy",
            name="caf",
        ),
        migrations.AddField(
            model_name="incentiveagendaproduct",
            name="agenda",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agenda_product",
                to="incentive.incentiveagenda",
            ),
        ),
        migrations.AddField(
            model_name="incentiveslecproduct",
            name="slec_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_product",
                to="incentive.incentiveslecorder",
            ),
        ),
        migrations.AddField(
            model_name="incentiveslecyealy",
            name="slec_order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_yearly_incentive",
                to="incentive.incentiveslecorder",
            ),
        ),
    ]
