# Generated by Django 5.1.5 on 2025-05-09 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0024_remove_incentiveagendaproduct_caf_and_more"),
        ("sws", "0053_sector_incentive_method_sector_sector_multiple_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectorIncentiveList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_header",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("icon_message", models.TextField(blank=True, null=True)),
                ("input_type", models.CharField(blank=True, max_length=20, null=True)),
                ("input_options", models.TextField(blank=True, null=True)),
                ("display_options", models.BooleanField(default=True)),
                (
                    "placeholder",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("display_order", models.SmallIntegerField(default=999)),
                (
                    "status",
                    models.CharField(
                        default="active",
                        help_text="active or inactive etc",
                        max_length=10,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incentive_sector_list",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "calculator_incentive_sector_list",
            },
        ),
    ]
