# Generated by Django 5.1.5 on 2025-05-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0025_sectorincentivelist"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectorincentivelist",
            name="input_tag",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
