# Generated by Django 5.1.5 on 2025-05-11 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0026_sectorincentivelist_input_tag"),
        ("sws", "0053_sector_incentive_method_sector_sector_multiple_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafemployment",
            name="no_of_employee_before_expansion",
            field=models.IntegerField(help_text="employee before expansion", null=True),
        ),
        migrations.AddField(
            model_name="incafemployment",
            name="no_of_employee_under_expansion",
            field=models.IntegerField(help_text="employee under expansion", null=True),
        ),
        migrations.AddField(
            model_name="incafemployment",
            name="total_no_of_employee_under_expansion",
            field=models.IntegerField(
                help_text="total no employee under expansion", null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="total_investment_electrical",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="total_investment_land",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="total_investment_other_asset",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="turnover",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafproduct",
            name="other_measurement_unit_name",
            field=models.CharField(
                blank=True,
                help_text="Measurement unit names",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafemployment",
            name="caf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incaf_employment",
                to="incentive.incentivecaf",
            ),
        ),
        migrations.AlterField(
            model_name="incafincentive",
            name="caf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incaf_incentive",
                to="incentive.incentivecaf",
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="caf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incaf_investment",
                to="incentive.incentivecaf",
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="period_from",
            field=models.DateField(blank=True, help_text="Period From Date", null=True),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="period_to",
            field=models.DateField(blank=True, help_text="Period to Date", null=True),
        ),
        migrations.AlterField(
            model_name="incafpower",
            name="caf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incaf_power",
                to="incentive.incentivecaf",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="caf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caf_project",
                to="incentive.incentivecaf",
            ),
        ),
        migrations.AlterField(
            model_name="incentivecaf",
            name="intention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incentive_intention_id",
                to="sws.customerintentionproject",
            ),
        ),
        migrations.CreateModel(
            name="InCAFExpansion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_of_production",
                    models.DateField(
                        blank=True, help_text="Commercial Production Date", null=True
                    ),
                ),
                ("expansion_no", models.SmallIntegerField(default=1)),
                (
                    "period_from",
                    models.DateField(
                        blank=True, help_text="Period From Date", null=True
                    ),
                ),
                (
                    "period_to",
                    models.DateField(blank=True, help_text="Period to Date", null=True),
                ),
                (
                    "total_investment_land",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "investment_in_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "investment_in_plant_machinery",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_investment_electrical",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_investment_other_asset",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_investment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "turnover",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_expansion",
                        to="incentive.incentivecaf",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_caf_expansion_details",
            },
        ),
        migrations.CreateModel(
            name="InCAFExpansionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "measurement_unit_name",
                    models.CharField(
                        blank=True,
                        help_text="Measurement unit names",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "other_measurement_unit_name",
                    models.CharField(
                        blank=True,
                        help_text="Measurement unit names",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(help_text="Product Name", max_length=255),
                ),
                (
                    "annual_capacity_before_expansion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Capacity befor expansion",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "annual_capacity_during_expansion",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Capacity during expansion",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_annual_capacity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Annual Capacity",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_expansion_products",
                        to="incentive.incentivecaf",
                    ),
                ),
                (
                    "measurement_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_expansion_measurement",
                        to="sws.measurementunitlist",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_caf_expansion_product_details",
            },
        ),
    ]
