# Generated by Django 5.1.5 on 2025-05-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0027_incafemployment_no_of_employee_before_expansion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafemployment",
            name="employee_domicile_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Domicile percentage",
                max_digits=10,
                null=True,
            ),
        ),
    ]
