# Generated by Django 5.1.5 on 2025-05-11 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0031_customuserprofile_dob_customuserprofile_father_name_and_more",
        ),
        ("incentive", "0028_incafemployment_employee_domicile_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafproject",
            name="md_contact_email",
            field=models.EmailField(
                default="", help_text="Email of md person", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="incafproject",
            name="md_contact_mobile_no",
            field=models.CharField(
                default="", help_text="Mobile number of md person", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="incafproject",
            name="md_country_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="md_country_code",
                to="authentication.country",
            ),
        ),
        migrations.AddField(
            model_name="incafproject",
            name="md_country_code_name",
            field=models.CharField(
                blank=True, default="", help_text="Code value", max_length=15
            ),
        ),
        migrations.AddField(
            model_name="incafproject",
            name="md_person_name",
            field=models.CharField(
                default="", help_text="Name of md person", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="country_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auth_country_code",
                to="authentication.country",
            ),
        ),
    ]
