# Generated by Django 5.1.5 on 2025-05-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0029_incafproject_md_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incafemployment",
            name="no_of_employee_before_expansion",
            field=models.IntegerField(
                blank=True, help_text="employee before expansion", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafemployment",
            name="no_of_employee_under_expansion",
            field=models.IntegerField(
                blank=True, help_text="employee under expansion", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafemployment",
            name="total_no_of_employee_under_expansion",
            field=models.IntegerField(
                blank=True, help_text="total no employee under expansion", null=True
            ),
        ),
    ]
