# Generated by Django 5.1.5 on 2025-05-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incentive",
            "0030_alter_incafemployment_no_of_employee_before_expansion_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="incafpower",
            name="connection_type",
            field=models.CharField(
                blank=True, help_text="New or Existing", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafpower",
            name="date_of_connection",
            field=models.DateField(
                blank=True, help_text="Date of connection", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafpower",
            name="ht_contract_demand",
            field=models.CharField(
                blank=True, help_text="11KV, 33KV etc", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="md_contact_email",
            field=models.EmailField(
                blank=True, help_text="Email of md person", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="md_contact_mobile_no",
            field=models.CharField(
                blank=True,
                help_text="Mobile number of md person",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="md_country_code_name",
            field=models.CharField(
                blank=True, help_text="Code value", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="md_person_name",
            field=models.CharField(
                blank=True, help_text="Name of md person", max_length=200, null=True
            ),
        ),
    ]
