# Generated by Django 5.1.5 on 2025-05-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0031_alter_incafpower_connection_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incafexpansionproduct",
            name="caf",
        ),
        migrations.AddField(
            model_name="incafexpansionproduct",
            name="expansion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expansion_products",
                to="incentive.incafexpansion",
            ),
        ),
    ]
