# Generated by Django 5.1.5 on 2025-05-16 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0032_remove_incafexpansionproduct_caf_and_more"),
        ("sws", "0056_alter_customerintentionproject_activity_and_more"),
        ("userprofile", "0018_organizationusermodel_country_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="incafemployment",
            name="employees_from_mp",
            field=models.IntegerField(
                blank=True, help_text="Employees from MP", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafemployment",
            name="employees_outside_mp",
            field=models.IntegerField(
                blank=True, help_text="Employees Outside From MP", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafemployment",
            name="total_employee",
            field=models.IntegerField(
                blank=True, help_text="Total Employee", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafincentive",
            name="is_gia",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incafincentive",
            name="is_ipp",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incafincentive",
            name="is_mandifee",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="comm_production_date",
            field=models.DateField(
                blank=True, help_text="Commercial Production Date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="investment_in_building",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="investment_in_plant_machinery",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="total_investment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproduct",
            name="product_name",
            field=models.CharField(
                blank=True, help_text="Product Name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_activity",
                to="sws.activity",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="activity_name",
            field=models.CharField(
                blank=True, help_text="activity name", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="address_of_unit",
            field=models.TextField(blank=True, help_text="Address of Unit", null=True),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block_district",
                to="sws.districtblocklist",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="block_name",
            field=models.CharField(
                blank=True, help_text="Block names", max_length=75, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="company_address",
            field=models.TextField(
                blank=True, help_text="Address of company", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="company_address_pincode",
            field=models.CharField(
                blank=True, help_text="Pincode of company", max_length=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="constitution_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="org_type_id",
                to="userprofile.organizationtype",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="constitution_type_name",
            field=models.CharField(
                blank=True,
                help_text="Constitution Type Name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Email of authorised person",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="contact_mobile_no",
            field=models.CharField(
                blank=True,
                help_text="Mobile number of authorised person",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="contact_person_name",
            field=models.CharField(
                blank=True,
                help_text="Name of authorised person",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="country_code_name",
            field=models.CharField(
                blank=True, help_text="Code value", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="date_of_intention",
            field=models.DateField(
                blank=True, help_text="Date of filled Intention", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_district",
                to="sws.district",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="district_name",
            field=models.CharField(
                blank=True, help_text="District names", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="gstin",
            field=models.CharField(
                blank=True, default="", help_text="GST number", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="gstin_issue_date",
            field=models.DateField(blank=True, help_text="GST issue date", null=True),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="iem_a_date",
            field=models.DateField(blank=True, help_text="IEM Part A Date", null=True),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="iem_a_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IEM Part A Number",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="iem_b_date",
            field=models.DateField(blank=True, help_text="IEM Part B Date", null=True),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="iem_b_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IEM Part B Number",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="industrial_area_name",
            field=models.CharField(
                blank=True, help_text="industrial area name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="industrial_plot",
            field=models.CharField(
                blank=True, help_text="industrial plot", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="intention_id",
            field=models.CharField(
                blank=True, help_text="Intention Id", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="land_type",
            field=models.CharField(
                blank=True, help_text="Land Type", max_length=75, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="regional_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_regional",
                to="sws.regionaloffice",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="regional_office_name",
            field=models.CharField(
                blank=True, help_text="District names", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_sector",
                to="sws.sector",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="sector_name",
            field=models.CharField(
                blank=True, help_text="Sector name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="sub_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="in_sub_sector",
                to="sws.subsector",
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="sub_sector_name",
            field=models.CharField(
                blank=True, help_text="Sub Sector name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="unit_name",
            field=models.CharField(
                blank=True, help_text="Company Name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="unit_type",
            field=models.CharField(
                blank=True, default="", help_text="unit_type", max_length=60, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafsubmeter",
            name="meter_number",
            field=models.CharField(
                blank=True, help_text="Sub meter details", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agenda_activity",
                to="sws.activity",
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="activity_name",
            field=models.CharField(
                blank=True, help_text="activity name", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="address_of_unit",
            field=models.TextField(blank=True, help_text="Address of Unit", null=True),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="application_filling_date",
            field=models.DateField(
                blank=True, help_text="Application Filling Date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="block_name",
            field=models.CharField(
                blank=True, help_text="Block names", max_length=75, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="category_of_block",
            field=models.CharField(
                blank=True,
                help_text="Priority or Non Priority",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="comm_production_date",
            field=models.DateField(
                blank=True, help_text="Commercial Production Date", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="constitution_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agendat_org_type_id",
                to="userprofile.organizationtype",
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="constitution_type_name",
            field=models.CharField(
                blank=True,
                help_text="Constitution Type Name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incaf_agenda_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="created_user_name",
            field=models.CharField(
                blank=True,
                help_text="name of user created the agenda",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="eligible_period",
            field=models.CharField(
                blank=True,
                help_text="Eligible Period of Assitance",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="first_production_year",
            field=models.CharField(
                blank=True, help_text="First product year", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="gstin_and_date",
            field=models.CharField(
                blank=True, help_text="GSTIN & Date", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="ht_contract_demand",
            field=models.CharField(
                blank=True,
                default="",
                help_text="11KV, 33KV etc",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="iem_a_date",
            field=models.DateField(blank=True, help_text="IEM Part A Date", null=True),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="iem_a_number",
            field=models.CharField(
                blank=True, help_text="IEM Part A Number", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="iem_b_date",
            field=models.DateField(blank=True, help_text="IEM Part B Date", null=True),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="iem_b_number",
            field=models.CharField(
                blank=True, help_text="IEM Part B Number", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="investment_in_plant_machinery",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="ipp",
            field=models.CharField(
                blank=True, help_text="IPP name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agenda_sector",
                to="sws.sector",
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="sector_name",
            field=models.CharField(
                blank=True, help_text="Sector name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="sub_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agenda_sub_sector",
                to="sws.subsector",
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="sub_sector_name",
            field=models.CharField(
                blank=True, help_text="SubSector name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="unit_name",
            field=models.CharField(
                blank=True, help_text="Company Name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="unit_type",
            field=models.CharField(
                blank=True, help_text="unit_type", max_length=60, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveapprovalhistory",
            name="incentive_action",
            field=models.CharField(
                blank=True,
                help_text="forward or raise query",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveapprovalhistory",
            name="next_approver_designation",
            field=models.CharField(
                blank=True, help_text="GM, CGM etc", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveauditlog",
            name="module",
            field=models.CharField(
                blank=True, help_text="module_name", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_activity",
                to="sws.activity",
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="activity_name",
            field=models.CharField(
                blank=True, help_text="activity name", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="category_of_block",
            field=models.CharField(
                blank=True,
                help_text="Priority or Non Priority",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="constitution_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_order_org_id",
                to="userprofile.organizationtype",
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="constitution_type_name",
            field=models.CharField(
                blank=True,
                help_text="Constitution Type Name",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="date_of_slec_meeting",
            field=models.DateField(
                blank=True, help_text="Date of Slec meeting", null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="eligibility_from",
            field=models.DateField(blank=True, help_text="elegibility from", null=True),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="eligibility_to",
            field=models.DateField(blank=True, help_text="elegibility to", null=True),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_sector",
                to="sws.sector",
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="sector_name",
            field=models.CharField(
                blank=True, help_text="Sector name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="slec_meeting_number",
            field=models.CharField(
                blank=True, help_text="Slec meeting number", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="sub_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_sub_sector",
                to="sws.subsector",
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="sub_sector_name",
            field=models.CharField(
                blank=True, help_text="Sub Sector name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="unit_name",
            field=models.CharField(
                blank=True, help_text="Company Name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="unit_type",
            field=models.CharField(
                blank=True, help_text="unit_type", max_length=60, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecproduct",
            name="slec_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_product",
                to="incentive.incentiveslecorder",
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecyealy",
            name="slec_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slec_yearly_incentive",
                to="incentive.incentiveslecorder",
            ),
        ),
    ]
