# Generated by Django 5.1.5 on 2025-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0033_alter_incafemployment_employees_from_mp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentivecaf",
            name="is_offline",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="sector_name",
            field=models.TextField(blank=True, help_text="Sector name", null=True),
        ),
        migrations.AlterField(
            model_name="incafproject",
            name="sub_sector_name",
            field=models.CharField(
                blank=True, help_text="Sub Sector name", max_length=250, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="sub_sector_name",
            field=models.TextField(blank=True, help_text="SubSector name", null=True),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="sub_sector_name",
            field=models.TextField(blank=True, help_text="Sub Sector name", null=True),
        ),
    ]
