# Generated by Django 5.1.5 on 2025-05-20 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0034_incentivecaf_is_offline_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InCAFSLECDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slec_doc_name",
                    models.CharField(
                        blank=True, help_text="Doc Name", max_length=255, null=True
                    ),
                ),
                (
                    "slec_doc_path",
                    models.TextField(blank=True, help_text="Document Path", null=True),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_slec_document",
                        to="incentive.incentivecaf",
                    ),
                ),
                (
                    "slec_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incaf_slec_document",
                        to="incentive.incentiveslecorder",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_caf_slec_documents",
            },
        ),
    ]
