# Generated by Django 5.1.5 on 2025-05-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0035_incafslecdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentiveslecorder",
            name="commencement_date",
            field=models.DateField(
                blank=True, help_text="commencement date", null=True
            ),
        ),
    ]
