# Generated by Django 5.1.5 on 2025-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0036_incentiveslecorder_commencement_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveClaimBasic",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "year_of_claimed_assistance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "employees_permanent_resident_of_mp",
                    models.IntegerField(blank=True, null=True),
                ),
                ("employees_outside_of_mp", models.IntegerField(blank=True, null=True)),
                ("total_employees", models.IntegerField(blank=True, null=True)),
                ("apply_date", models.DateTimeField()),
                ("action_date", models.DateTimeField()),
                ("action_by_id", models.BigIntegerField()),
                ("action_by_name", models.CharField(max_length=255)),
                (
                    "claim_pdf_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("acknowledgement_date", models.DateTimeField(blank=True, null=True)),
                ("acknowledgement", models.BooleanField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "incentive_claim_basic",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IncentiveDisbursement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("disbursement_date", models.DateField(blank=True, null=True)),
                (
                    "disbursed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "year_of_claimed_assistance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("action_by", models.BigIntegerField(blank=True, null=True)),
                (
                    "action_by_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("action_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "incentive_disbursement",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IncentiveSanctionOrder",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "sanction_order_no",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "sanction_order_created_date",
                    models.DateField(blank=True, null=True),
                ),
                ("unit_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "location_of_unit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "annual_yearly_investment_assistance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gross_supply_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "geographical_multiple",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "employement_multiple_for_the_claim_year",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "export_multiple_for_the_claim_year",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_sanctioned_assistance_amount_till_previous_year",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_sanctioned_assistance_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sanction_order_create_by",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "sanction_order_create_by_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("action_by", models.BigIntegerField(blank=True, null=True)),
                (
                    "action_by_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("action_date", models.DateField(blank=True, null=True)),
                ("sanction_order_esign_date", models.DateField(blank=True, null=True)),
                (
                    "sanction_order_final_pdf_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "sanction_order_creation_pdf_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "sanction_order_gm_pdf_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "sanction_order_cgm_pdf_id",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "type_of_unit",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "sanction_pdf_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("acknowledgement_date", models.DateField(blank=True, null=True)),
                ("acknowledgement", models.BooleanField(blank=True, null=True)),
                ("is_old_record", models.BooleanField(blank=True, null=True)),
                (
                    "year_of_claimed_assistance",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "incentive_sanction_order",
                "managed": False,
            },
        ),
    ]
