# Generated by Django 5.1.5 on 2025-05-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0037_incentiveclaimbasic_incentivedisbursement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveClaimProductDetail",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("production_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "production_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("sale_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "sale_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("export_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "export_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("gsm_percentage", models.FloatField(blank=True, null=True)),
                ("gsm_final_value", models.FloatField(blank=True, null=True)),
                ("export_percentage", models.FloatField(blank=True, null=True)),
                ("export_final_value", models.FloatField(blank=True, null=True)),
                ("apply_date", models.DateTimeField(blank=True, null=True)),
                ("action_date", models.DateTimeField(blank=True, null=True)),
                ("action_by_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "action_by_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "measurement_unit_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "total_annual_capacity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
            ],
            options={
                "db_table": "incentive_claim_product_details",
                "managed": False,
            },
        ),
    ]
