# Generated by Django 5.1.5 on 2025-05-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0038_incentiveclaimproductdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveOfflineApplications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intention_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("intention_date", models.DateField(blank=True, null=True)),
                ("unit_name", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_production", models.DateField(blank=True, null=True)),
                ("unit_type", models.CharField(blank=True, max_length=100, null=True)),
                ("activity", models.CharField(blank=True, max_length=100, null=True)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "block_priority",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("slec_meeting_date", models.DateField(blank=True, null=True)),
                (
                    "slec_meeting_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "eligible_investment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "basic_investment_promotion_assistance_cr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "yearly_basic_investment_promotion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("eligibility_start_date", models.DateField(blank=True, null=True)),
                ("eligibility_end_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "incentive_offline_applications",
            },
        ),
    ]
