# Generated by Django 5.1.5 on 2025-05-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0039_incentiveofflineapplications"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incentiveofflineapplications",
            old_name="basic_investment_promotion_assistance_cr",
            new_name="bipa",
        ),
        migrations.RenameField(
            model_name="incentiveofflineapplications",
            old_name="yearly_basic_investment_promotion",
            new_name="ybipa",
        ),
    ]
