# Generated by Django 5.1.5 on 2025-05-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incentive",
            "0040_rename_basic_investment_promotion_assistance_cr_incentiveofflineapplications_bipa_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="incentiveactivityhistory",
            name="mac_address",
            field=models.CharField(
                blank=True, help_text="mac address", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="incentiveauditlog",
            name="mac_address",
            field=models.CharField(
                blank=True, help_text="mac address", max_length=200, null=True
            ),
        ),
    ]
