# Generated by Django 5.1.5 on 2025-05-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0041_incentiveactivityhistory_mac_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPAUnitDataMaster",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="S._No.", primary_key=True, serialize=False
                    ),
                ),
                (
                    "intention_id",
                    models.TextField(blank=True, db_column="Intention_ID", null=True),
                ),
                (
                    "intention_date",
                    models.TextField(blank=True, db_column="Intention Date", null=True),
                ),
                (
                    "unit_name",
                    models.TextField(blank=True, db_column="Unit  Name", null=True),
                ),
                (
                    "unit_type",
                    models.TextField(blank=True, db_column="Type", null=True),
                ),
                (
                    "date_of_production",
                    models.TextField(
                        blank=True, db_column="Date of Production", null=True
                    ),
                ),
                ("sector", models.TextField(blank=True, db_column="Sector", null=True)),
                (
                    "product_name",
                    models.TextField(blank=True, db_column="Product Name", null=True),
                ),
                (
                    "block_priority",
                    models.TextField(
                        blank=True, db_column="Priority Block (Y/N)", null=True
                    ),
                ),
                (
                    "slec_meeting_no",
                    models.TextField(
                        blank=True, db_column="SLEC Meeting Number", null=True
                    ),
                ),
                (
                    "slec_meeting_date",
                    models.TextField(
                        blank=True, db_column="SLEC Meeting Date", null=True
                    ),
                ),
                (
                    "eligibility_start_date",
                    models.TextField(
                        blank=True, db_column="Eligibility Period Start", null=True
                    ),
                ),
                (
                    "eligibility_end_date",
                    models.TextField(
                        blank=True, db_column="Eligibility Period End", null=True
                    ),
                ),
                (
                    "eligible_investment",
                    models.IntegerField(
                        blank=True,
                        db_column="Eligible Investment Rs. In Lakh.",
                        null=True,
                    ),
                ),
                (
                    "bipa",
                    models.IntegerField(
                        blank=True, db_column="Basic IPA Rs. In Lakh", null=True
                    ),
                ),
                (
                    "ybipa",
                    models.IntegerField(blank=True, db_column="Yearly BIPA", null=True),
                ),
                (
                    "claim_fy",
                    models.TextField(blank=True, db_column="Claim FY", null=True),
                ),
                (
                    "sanctioned_date",
                    models.TextField(
                        blank=True, db_column="Sanctioned Date", null=True
                    ),
                ),
                (
                    "sanctioned_amount",
                    models.FloatField(
                        blank=True, db_column="Sanctioned Amount  (IN Lakh)", null=True
                    ),
                ),
                (
                    "disbursement_date",
                    models.TextField(
                        blank=True, db_column="Disbursement Date", null=True
                    ),
                ),
                (
                    "disbursed_amount",
                    models.IntegerField(
                        blank=True, db_column="Disbursed Amount (In Lakh)", null=True
                    ),
                ),
                ("remark", models.TextField(blank=True, db_column="Remark", null=True)),
            ],
            options={
                "db_table": "IPA_Unit_Data_Master",
                "managed": False,
            },
        ),
    ]
