# Generated by Django 5.1.5 on 2025-05-29 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0042_ipaunitdatamaster"),
        ("sws", "0057_alter_cafinvestmentdetails_sub_sector_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveDepartmentQueryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "query_type",
                    models.CharField(
                        blank=True,
                        help_text="In-Progress, Completed, Deleted",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="In-Progress, Completed, Deleted",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, help_text="name of user", max_length=255, null=True
                    ),
                ),
                (
                    "department_user_name",
                    models.CharField(
                        blank=True,
                        help_text="department user name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "user_remark",
                    models.TextField(blank=True, help_text="User Remark", null=True),
                ),
                (
                    "department_remark",
                    models.TextField(
                        blank=True, help_text="Department Remark", null=True
                    ),
                ),
                (
                    "depratment_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incentive_query_department_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="query_intention_id",
                        to="sws.customerintentionproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incentive_query_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "incentive_department_queries",
            },
        ),
        migrations.CreateModel(
            name="IncentiveQueryDocumentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_name",
                    models.CharField(
                        blank=True, help_text="document path", max_length=255, null=True
                    ),
                ),
                (
                    "document_path",
                    models.TextField(blank=True, help_text="document path", null=True),
                ),
                (
                    "query",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queries",
                        to="incentive.incentivedepartmentquerymodel",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_query_documents",
            },
        ),
    ]
