# Generated by Django 5.1.5 on 2025-05-30 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0031_customuserprofile_dob_customuserprofile_father_name_and_more",
        ),
        ("incentive", "0043_incentivedepartmentquerymodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentivedepartmentquerymodel",
            name="caf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_caf",
                to="incentive.incentivecaf",
            ),
        ),
        migrations.AddField(
            model_name="incentivedepartmentquerymodel",
            name="department_user_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="query_user_role",
                to="authentication.role",
            ),
        ),
    ]
