# Generated by Django 5.1.5 on 2025-05-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0044_incentivedepartmentquerymodel_caf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incafexpansionproduct",
            name="product_name",
            field=models.TextField(help_text="Product Name"),
        ),
        migrations.AlterField(
            model_name="incafproduct",
            name="product_name",
            field=models.TextField(blank=True, help_text="Product Name", null=True),
        ),
        migrations.AlterField(
            model_name="incentiveagendaproduct",
            name="product_name",
            field=models.TextField(blank=True, help_text="Product Name", null=True),
        ),
        migrations.AlterField(
            model_name="incentiveslecproduct",
            name="product_name",
            field=models.TextField(blank=True, help_text="Product Name", null=True),
        ),
    ]
