# Generated by Django 5.1.5 on 2025-06-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0045_alter_incafexpansionproduct_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incafexpansionproduct",
            name="annual_capacity_before_expansion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Capacity befor expansion",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafexpansionproduct",
            name="annual_capacity_during_expansion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Capacity during expansion",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafexpansionproduct",
            name="total_annual_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual Capacity",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafproduct",
            name="total_annual_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual Capacity",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagendaproduct",
            name="total_annual_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual Capacity",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecproduct",
            name="total_annual_capacity",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual Capacity",
                max_digits=19,
                null=True,
            ),
        ),
    ]
