# Generated by Django 5.1.5 on 2025-06-09 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0031_customuserprofile_dob_customuserprofile_father_name_and_more",
        ),
        (
            "incentive",
            "0046_alter_incafexpansionproduct_annual_capacity_before_expansion_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveSLECArrearModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incentive_year",
                    models.CharField(
                        blank=True, help_text="incentive year", max_length=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="In-Progress, Completed, Deleted",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "department_user_name",
                    models.CharField(
                        blank=True,
                        help_text="department user name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "department_remark",
                    models.TextField(
                        blank=True, help_text="Department Remark", null=True
                    ),
                ),
                (
                    "department_user_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrear_user_role",
                        to="authentication.role",
                    ),
                ),
                (
                    "depratment_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slec_arrear_department_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slec_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrear_slec_order",
                        to="incentive.incentiveslecorder",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_slec_order_arrears",
            },
        ),
    ]
