# Generated by Django 5.1.5 on 2025-06-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0047_incentiveslecarrearmodel"),
        ("sws", "0059_sector_incentive_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncentiveTypeMasterModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incentive_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        default="active",
                        help_text="active or inactive etc",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "incentive_type_master",
            },
        ),
        migrations.CreateModel(
            name="IncentiveTypeSectorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incentive_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incentive.incentivetypemastermodel",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incentive_type_sectors",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_type_based_on_sector",
            },
        ),
    ]
