# Generated by Django 5.1.5 on 2025-07-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0048_incentivetypemastermodel_incentivetypesectormodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incafemployment",
            old_name="no_of_employee_before_expansion",
            new_name="employee_from_mp_before_expansion",
        ),
        migrations.RenameField(
            model_name="incafemployment",
            old_name="no_of_employee_under_expansion",
            new_name="employees_outside_mp_before_expansion",
        ),
        migrations.RenameField(
            model_name="incafemployment",
            old_name="total_no_of_employee_under_expansion",
            new_name="total_employee_before_expansion",
        ),
        migrations.RemoveField(
            model_name="incafemployment",
            name="employee_domicile_percentage",
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="csr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="fdi_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="fdi_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="is_export_unit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="is_fdi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="promoters_equity_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="term_loan_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="total_finance_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafexpansion",
            name="investment_in_building",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafexpansion",
            name="investment_in_plant_machinery",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafexpansion",
            name="total_investment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafexpansion",
            name="total_investment_electrical",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafexpansion",
            name="total_investment_land",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafexpansion",
            name="total_investment_other_asset",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafexpansion",
            name="turnover",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafincentive",
            name="wms_total_expenditure",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="is_gia true then wms expenditure needed",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="investment_in_building",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="investment_in_plant_machinery",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="total_investment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="total_investment_electrical",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="total_investment_land",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="total_investment_other_asset",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafinvestment",
            name="turnover",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incafpower",
            name="additional_load",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Additional Load consumption",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafpower",
            name="existing_load",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Existing Load consumption",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafpower",
            name="load_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Load consumption",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incafpowerload",
            name="supplementary_load",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Supplementary Saction load",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="bipa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="eligible_investment_plant_machinery",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="investment_in_plant_machinery",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="percentage_in_employee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="saction_power_load",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="decimal values",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="yearly_bipa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="bipa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="eligible_investment_plant_machinery",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecorder",
            name="yearly_bipa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="incentiveslecyealy",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Incentive",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incentivetypemastermodel",
            name="incentive_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
