# Generated by Django 5.1.5 on 2025-07-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incentive",
            "0049_rename_no_of_employee_before_expansion_incafemployment_employee_from_mp_before_expansion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="incafemployment",
            name="employee_domicile_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Domicile percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incafemployment",
            name="employee_domicile_percentage_before_expansion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Domicile percentage before expansion",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incafincentive",
            name="incentive_json",
            field=models.JSONField(blank=True, help_text="store json data", null=True),
        ),
        migrations.AddField(
            model_name="incafpower",
            name="connection_type_before_expansion",
            field=models.CharField(
                blank=True, help_text="Before expansion", max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafpower",
            name="date_of_connection_before_expansion",
            field=models.DateField(blank=True, help_text="Before expansion", null=True),
        ),
        migrations.AddField(
            model_name="incafpower",
            name="meter_before_expansion",
            field=models.CharField(
                blank=True,
                help_text="Meter details before expansion",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incafpower",
            name="power_load_before_expansion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Load before expansion",
                max_digits=12,
                null=True,
            ),
        ),
    ]
