# Generated by Django 5.1.5 on 2025-07-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0050_incafemployment_employee_domicile_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentivetypesectormodel",
            name="display_order",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
