# Generated by Django 5.1.5 on 2025-07-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0051_incentivetypesectormodel_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentivecaf",
            name="is_document_sign",
            field=models.BooleanField(default=False),
        ),
    ]
