# Generated by Django 5.1.5 on 2025-07-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0052_incentivecaf_is_document_sign"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafproject",
            name="is_ccip",
            field=models.BooleanField(default=False),
        ),
    ]
