# Generated by Django 5.1.5 on 2025-07-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0053_incafproject_is_ccip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectordocumentlist",
            name="doc_type",
            field=models.CharField(
                default="Common", help_text="Common, GIA etc", max_length=50
            ),
        ),
    ]
