# Generated by Django 5.1.5 on 2025-07-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0054_alter_sectordocumentlist_doc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafemployment",
            name="number_of_differently_abled_employees",
            field=models.IntegerField(
                blank=True, help_text="Number of differently abled employees", null=True
            ),
        ),
        migrations.AddField(
            model_name="incafemployment",
            name="percentage_of_differently_abled_employees",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentange of differently abled employees",
                max_digits=5,
                null=True,
            ),
        ),
    ]
