# Generated by Django 5.1.5 on 2025-07-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incentive",
            "0055_incafemployment_number_of_differently_abled_employees_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_in_building_before_expansion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_in_plant_machinery_before_expansion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_land_before_expansion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_other_asset_before_expansion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="total_investment_amount_before_expansion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafproduct",
            name="annual_capacity_before_expansion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Annual Capacity Before Capacity",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incafproduct",
            name="avg_production_before_expansion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Avg Before Capacity",
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incafproduct",
            name="ime_before_expansion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="IME Before Capacity",
                max_digits=19,
                null=True,
            ),
        ),
    ]
