# Generated by Django 5.1.5 on 2025-07-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incentive",
            "0056_incafinvestment_investment_in_building_before_expansion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_etp_stp_pcd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_furniture_fixtures",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
