# Generated by Django 5.1.5 on 2025-07-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0057_incafinvestment_investment_etp_stp_pcd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafpower",
            name="meter_details",
            field=models.CharField(
                blank=True, help_text="Meter details", max_length=255, null=True
            ),
        ),
    ]
