# Generated by Django 5.1.5 on 2025-07-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0058_incafpower_meter_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafinvestment",
            name="is_csr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incafproject",
            name="dipip_type",
            field=models.CharField(
                blank=True, help_text="DIPIP type of land", max_length=255, null=True
            ),
        ),
    ]
