# Generated by Django 5.1.5 on 2025-07-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0059_incafinvestment_is_csr_incafproject_dipip_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafpowerload",
            name="is_supplementary_load",
            field=models.BooleanField(default=False),
        ),
    ]
