# Generated by Django 5.1.5 on 2025-07-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0060_incafpowerload_is_supplementary_load"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafproduct",
            name="product_type",
            field=models.CharField(blank=True, default="New", max_length=50, null=True),
        ),
    ]
