# Generated by Django 5.1.5 on 2025-07-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0061_incafproduct_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafpower",
            name="enhancement_load_date",
            field=models.DateField(
                blank=True, help_text="Data of load enhancement", null=True
            ),
        ),
    ]
