# Generated by Django 5.1.5 on 2025-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0062_incafpower_enhancement_load_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafproject",
            name="plot_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
