# Generated by Django 5.1.5 on 2025-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0063_incafproject_plot_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafproject",
            name="designation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="incafproject",
            name="other_designation",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
