# Generated by Django 5.1.5 on 2025-07-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0064_incafproject_designation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incafinvestment",
            name="full_investment_captive_power",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="full_investment_energy_saving_devices",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="full_investment_imported_second_hand_machinery",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="full_investment_in_house",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="full_investment_refurbishment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_captive_power_before_expansion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_energy_saving_devices_before_expansion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_imported_second_hand_machinery_before_expansion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_in_house_before_expansion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="investment_refurbishment_before_expansion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
