# Generated by Django 5.1.5 on 2025-07-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0065_incafinvestment_full_investment_captive_power_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incafinvestment",
            old_name="full_investment_captive_power",
            new_name="investment_captive_power",
        ),
        migrations.RenameField(
            model_name="incafinvestment",
            old_name="full_investment_energy_saving_devices",
            new_name="investment_energy_saving_devices",
        ),
        migrations.RenameField(
            model_name="incafinvestment",
            old_name="full_investment_imported_second_hand_machinery",
            new_name="investment_imported_second_hand_machinery",
        ),
        migrations.RenameField(
            model_name="incafinvestment",
            old_name="full_investment_in_house",
            new_name="investment_in_house",
        ),
        migrations.RenameField(
            model_name="incafinvestment",
            old_name="full_investment_refurbishment",
            new_name="investment_refurbishment",
        ),
    ]
