# Generated by Django 5.1.5 on 2025-07-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "incentive",
            "0066_rename_full_investment_captive_power_incafinvestment_investment_captive_power_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="incentiveagenda",
            name="is_document_sign",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="incentiveagenda",
            name="agenda_file",
            field=models.TextField(blank=True, null=True),
        ),
    ]
