# Generated by Django 5.1.5 on 2025-07-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0067_incentiveagenda_is_document_sign_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incafinvestment",
            name="investment_etp_stp_pcd",
        ),
        migrations.RemoveField(
            model_name="incafinvestment",
            name="period_from",
        ),
        migrations.RemoveField(
            model_name="incafinvestment",
            name="period_to",
        ),
        migrations.RemoveField(
            model_name="incafinvestment",
            name="total_investment_electrical",
        ),
        migrations.AddField(
            model_name="incafinvestment",
            name="other_assets_remark",
            field=models.CharField(
                blank=True, help_text="Other Assets Remarks", max_length=255, null=True
            ),
        ),
    ]
