# Generated by Django 5.1.5 on 2025-08-07 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0068_remove_incafinvestment_investment_etp_stp_pcd_and_more"),
        ("sws", "0065_customerintentionproject_intention_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentiveagenda",
            name="block",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agenda_block_district",
                to="sws.districtblocklist",
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agenda_district",
                to="sws.district",
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="district_name",
            field=models.CharField(
                blank=True, help_text="District names", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="employee_domicile_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Domicile percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="employee_domicile_percentage_before_expansion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Domicile percentage before expansion",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="employee_of_mp_before_expansion",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="employee_outside_mp_before_expansion",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="industrial_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agenda_industrial_area",
                to="sws.industrialarealist",
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="industrial_area_name",
            field=models.CharField(
                blank=True, help_text="industrial area name", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="industrial_plot",
            field=models.CharField(
                blank=True, help_text="industrial plot", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="land_type",
            field=models.CharField(
                blank=True, help_text="Land Type", max_length=75, null=True
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="number_of_differently_abled_employees",
            field=models.IntegerField(
                blank=True, help_text="Number of differently abled employees", null=True
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="percentage_of_differently_abled_employees",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentange of differently abled employees",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="plot_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="regional_office",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agenda_regional",
                to="sws.regionaloffice",
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="regional_office_name",
            field=models.CharField(
                blank=True, help_text="District names", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="incentiveagenda",
            name="total_employee_before_expansion",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AgendaIncentiveModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incentive_json",
                    models.JSONField(
                        blank=True, help_text="store json data", null=True
                    ),
                ),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_incentive",
                        to="incentive.incentiveagenda",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_agenda_assistance",
            },
        ),
        migrations.CreateModel(
            name="AgendaInvestmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_ccip", models.BooleanField(default=False)),
                (
                    "turnover",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_export_unit", models.BooleanField(default=False)),
                ("is_csr", models.BooleanField(default=False)),
                ("csr", models.CharField(blank=True, max_length=100, null=True)),
                ("is_fdi", models.BooleanField(default=False)),
                (
                    "promoters_equity_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "term_loan_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "fdi_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "fdi_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "total_finance_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "investment_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "eligible_investment_building",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "investment_plant_machinery",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "eligible_investment_plant_machinery",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "investment_inhouse_rnd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "eligible_investment_inhouse_rnd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "investment_captive_power",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "eligible_investment_captive_power",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "investment_energy_saving_devices",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "eligible_investment_energy_saving_devices",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "investment_imported_second_hand_machinery",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "eligible_investment_imported_second_hand_machinery",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "investment_refurbishment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "eligible_investment_refurbishment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "agenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_investment",
                        to="incentive.incentiveagenda",
                    ),
                ),
            ],
            options={
                "db_table": "incentive_agenda_investment",
            },
        ),
    ]
