# Generated by Django 5.1.5 on 2025-08-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0069_incentiveagenda_block_incentiveagenda_district_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incentiveagenda",
            name="employee_domicile_percentage",
        ),
    ]
