# Generated by Django 5.1.5 on 2025-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0070_remove_incentiveagenda_employee_domicile_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="agendainvestmentmodel",
            name="investment_furniture_fixtures",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
