# Generated by Django 5.1.5 on 2025-08-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0071_agendainvestmentmodel_investment_furniture_fixtures"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentivetypemastermodel",
            name="incentive_validity",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
