# Generated by Django 5.1.5 on 2025-08-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0072_incentivetypemastermodel_incentive_validity"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentivetypesectormodel",
            name="show_in_claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="incentivetypesectormodel",
            name="show_in_incentive",
            field=models.BooleanField(default=False),
        ),
    ]
