# Generated by Django 5.1.5 on 2025-08-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0073_incentivetypesectormodel_show_in_claim_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CcipIndustrialUnitGeneralInfo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "intention_to_invest_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("request_date", models.DateField(blank=True, null=True)),
                (
                    "name_of_industrial_unit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "applicant_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("constitution_type_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "constitution_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "address_line",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("district_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("city_id", models.BigIntegerField(blank=True, null=True)),
                ("city_name", models.CharField(blank=True, max_length=50, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "category_of_block",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("action_by_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "action_by_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("action_date", models.DateField(blank=True, null=True)),
                ("doc_url", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "signed_doc_url",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
            options={
                "db_table": "ccip_industrial_unit_general_info",
                "managed": False,
            },
        ),
    ]
