# Generated by Django 5.1.5 on 2025-08-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0074_ccipindustrialunitgeneralinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="incentivecaf",
            name="is_instruction_acknowledgement",
            field=models.BooleanField(default=False),
        ),
    ]
