# Generated by Django 5.1.5 on 2025-02-06 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_customuserprofile_mobile_no"),
        ("sws", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreEstablishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sector_of_business", models.CharField(max_length=255)),
                ("nature_of_business", models.TextField(blank=True, null=True)),
                ("constitution_unit", models.CharField(max_length=60)),
                ("is_land", models.BooleanField(default=False)),
                ("type_of_land", models.CharField(max_length=60)),
                ("pvt_land_location", models.CharField(max_length=60)),
                ("water_source", models.TextField()),
                ("line_of_activity", models.CharField(max_length=280)),
                ("pollution_category", models.CharField(max_length=255)),
                ("Investment", models.CharField(max_length=100)),
                ("power_req", models.CharField(max_length=60)),
                ("proposed_employment", models.CharField(max_length=100)),
                ("is_building_height", models.BooleanField(default=False)),
                ("tree_felling_proposed", models.BooleanField(default=False)),
                ("risk_category", models.CharField(max_length=255)),
                ("firm_size", models.CharField(max_length=60)),
                ("business_location", models.CharField(max_length=255)),
                ("investor_type", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.customuserprofile",
                    ),
                ),
            ],
            options={
                "db_table": "sws_pre_establishments",
            },
        ),
        migrations.CreateModel(
            name="PreOperational",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employ_migrant_workman", models.BooleanField()),
                ("employ_contractual_workers", models.BooleanField()),
                ("employ_building_construction", models.BooleanField()),
                ("employee_annual_salary", models.BooleanField()),
                ("turn_over", models.BooleanField()),
                ("boiler_job_type", models.TextField()),
                ("power_installation", models.BooleanField()),
                ("wm_job_type", models.TextField()),
                ("is_investment", models.BooleanField()),
                ("is_etp_stp", models.BooleanField()),
                ("is_unit_cold_chain", models.BooleanField()),
                ("is_textile_unit", models.BooleanField()),
                ("is_dipip_approved", models.BooleanField()),
                ("risk_category", models.CharField(max_length=255)),
                ("firm_size", models.CharField(max_length=60)),
                ("business_location", models.CharField(max_length=255)),
                ("investor_type", models.CharField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.customuserprofile",
                    ),
                ),
            ],
            options={
                "db_table": "sws_pre_operational",
            },
        ),
    ]
