# Generated by Django 5.1.5 on 2025-02-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0003_alter_preestablishment_user_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerIntentionProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_of_activity",
                    models.CharField(
                        choices=[
                            ("Manufacturing", "Manufacturing"),
                            ("Service", "Service"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            (
                                "Foods, processed agricultural or marine products",
                                "Foods, processed agricultural or marine products",
                            )
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        choices=[
                            ("Product 1", "Product 1"),
                            ("Product 2", "Product 2"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "pollution_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("product_proposed_date", models.DateTimeField(auto_now=True)),
                ("project_name", models.CharField(max_length=255)),
                ("project_description", models.TextField()),
                ("differently_abled", models.BooleanField(default=False)),
                ("minority", models.BooleanField(default=False)),
                ("caf_id", models.IntegerField()),
                ("woman_entrepreneur", models.BooleanField()),
            ],
            options={
                "db_table": "caf_project_information",
            },
        ),
        migrations.CreateModel(
            name="SiteLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot_number", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("tehsil", models.CharField(blank=True, max_length=100, null=True)),
                ("village", models.CharField(max_length=100)),
                ("pin_code", models.CharField(max_length=255)),
                ("total_open_area", models.IntegerField()),
                ("total_land_area", models.IntegerField()),
                ("total_covered_area", models.BooleanField(default=False)),
                ("building_height", models.IntegerField()),
                ("building_plan_approval", models.BooleanField()),
                ("caf_id", models.IntegerField()),
                (
                    "customer_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sws.customerintentionproject",
                    ),
                ),
            ],
            options={
                "db_table": "caf_site_location",
            },
        ),
    ]
