# Generated by Django 5.1.5 on 2025-02-07 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0004_customerintentionproject_sitelocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CAF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("Company", "COMPANY"),
                            ("Partnership", "PARTNERSHIP"),
                            ("Proprietorship", "PROPRIETORSHIP"),
                        ],
                        max_length=50,
                    ),
                ),
                ("registered_under_msme", models.BooleanField(default=False)),
                (
                    "msme_registration_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("firm_registration_number", models.CharField(max_length=255)),
                ("registration_date", models.DateField()),
                (
                    "scale_of_industry",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("firm_pan_number", models.CharField(max_length=10)),
                ("firm_gstin_number", models.CharField(max_length=15)),
                ("website_url", models.URLField()),
                ("helpdesk_number", models.CharField(max_length=15)),
                ("firm_email_id", models.EmailField(max_length=254)),
            ],
            options={
                "db_table": "caf_detail",
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "caf_designation",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_line", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("pin_code", models.CharField(max_length=6)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("Registered", "Registered Office"),
                            ("Communication", "Communication"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caf_address",
                        to="sws.caf",
                    ),
                ),
            ],
            options={
                "db_table": "caf_addess",
            },
        ),
        migrations.CreateModel(
            name="CommonApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                ("mobile_number", models.CharField(max_length=15)),
                ("email_id", models.EmailField(max_length=254)),
                ("aadhaar_number", models.CharField(max_length=12)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("Director", "Director"),
                            ("Manager", "Manager"),
                            ("Partner", "Partner"),
                            ("Proprietor", "Proprietor"),
                            ("Authorized", "Authorized"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caf_contact_detail",
                        to="sws.caf",
                    ),
                ),
            ],
            options={
                "db_table": "caf_contact_detail",
            },
        ),
    ]
