# Generated by Django 5.1.5 on 2025-02-09 14:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0007_activity_investmentrange_pollutiontype_sector_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerintentionproject",
            name="caf_id",
        ),
        migrations.RemoveField(
            model_name="customerintentionproject",
            name="line_of_activity",
        ),
        migrations.RemoveField(
            model_name="sitelocation",
            name="address",
        ),
        migrations.RemoveField(
            model_name="sitelocation",
            name="building_plan_approval",
        ),
        migrations.RemoveField(
            model_name="sitelocation",
            name="caf_id",
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="activity",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="employment",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="intention_id",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="plant_machinery_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="power_required",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="status",
            field=models.CharField(default="new", max_length=20),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="total_investment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="total_investment_range",
            field=models.CharField(default="Less than 1 Cr.", max_length=50),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="water_required",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="sitelocation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="sitelocation",
            name="industrial_area",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitelocation",
            name="regional_office",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="sitelocation",
            name="type_of_land",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="sitelocation",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="product_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="sector",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="woman_entrepreneur",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sitelocation",
            name="district",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitelocation",
            name="pin_code",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="sitelocation",
            name="plot_number",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="sitelocation",
            name="total_covered_area",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="sitelocation",
            name="village",
            field=models.CharField(default="", max_length=100),
        ),
    ]
