# Generated by Django 5.1.5 on 2025-02-10 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0009_customerintentionproject_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                (
                    "status",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sws_department",
            },
        ),
        migrations.CreateModel(
            name="ServiceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Pre-Operational", "Pre-Operational"),
                            ("Pre-Establishment", "Pre-Establishment"),
                        ],
                        default="Pre-Establishment",
                        max_length=30,
                    ),
                ),
                ("act_name", models.TextField(default="")),
                ("timeline", models.CharField(default="", max_length=20)),
                (
                    "status",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_service",
                        to="sws.departmentlist",
                    ),
                ),
            ],
            options={
                "db_table": "sws_services",
            },
        ),
        migrations.CreateModel(
            name="SectorServiceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="sws.sector",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="sws.servicelist",
                    ),
                ),
            ],
            options={
                "db_table": "sws_sector_services",
            },
        ),
        migrations.CreateModel(
            name="OtherServiceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition_type", models.CharField(default="", max_length=30)),
                (
                    "status",
                    models.BooleanField(
                        default=True, verbose_name="0 for inactive & 1 for active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_services",
                        to="sws.servicelist",
                    ),
                ),
            ],
            options={
                "db_table": "sws_other_services_mapping",
            },
        ),
    ]
