# Generated by Django 5.1.5 on 2025-02-11 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0010_departmentlist_servicelist_sectorservicelist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caf",
            name="intention",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.customerintentionproject",
            ),
        ),
    ]
