# Generated by Django 5.1.5 on 2025-02-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0011_caf_intention"),
    ]

    operations = [
        migrations.AddField(
            model_name="caf",
            name="status",
            field=models.CharField(default="Not Started", max_length=30),
        ),
    ]
