# Generated by Django 5.1.5 on 2025-02-12 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0012_caf_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CAFManufacturingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("Line of Manufacture", "Line of Manufacture"),
                            ("Raw Material", "Raw Material "),
                            ("Production Capacity", "Production Capacity"),
                        ],
                        default="Production Capacity",
                        max_length=30,
                    ),
                ),
                ("quantity", models.CharField(default="", max_length=20)),
                ("quantity_unit", models.CharField(default="", max_length=20)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caf_manufacturing_details",
                        to="sws.caf",
                    ),
                ),
            ],
            options={
                "db_table": "caf_manufacturing_details",
            },
        ),
        migrations.CreateModel(
            name="CAFProjectDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(default="", max_length=255)),
                ("activity", models.CharField(default="", max_length=100)),
                ("sector", models.CharField(default="", max_length=255)),
                ("line_of_activity", models.CharField(default="", max_length=255)),
                (
                    "pollution_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("product_proposed_date", models.DateTimeField(auto_now=True)),
                ("differently_abled", models.BooleanField(default=False)),
                ("minority", models.BooleanField(default=False)),
                ("woman_entrepreneur", models.BooleanField(default=False)),
                ("plot_number", models.CharField(default="", max_length=50)),
                ("industrial_area", models.CharField(default="", max_length=100)),
                ("district", models.CharField(default="", max_length=100)),
                ("tehsil", models.CharField(blank=True, max_length=100, null=True)),
                ("village", models.CharField(default="", max_length=100)),
                ("total_open_area", models.IntegerField()),
                ("total_land_area", models.IntegerField()),
                ("total_covered_area", models.IntegerField()),
                ("building_height", models.IntegerField()),
                ("land_value", models.CharField(default="", max_length=100)),
                ("building_value", models.CharField(default="", max_length=100)),
                ("plant_machinary_value", models.CharField(default="", max_length=100)),
                ("total_project_Value", models.CharField(default="", max_length=100)),
                ("total_project_Value_words", models.TextField(default="")),
                ("direct_male_employee", models.CharField(default="", max_length=100)),
                (
                    "direct_female_employee",
                    models.CharField(default="", max_length=100),
                ),
                (
                    "indirect_male_employee",
                    models.CharField(default="", max_length=100),
                ),
                (
                    "indirect_female_employee",
                    models.CharField(default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "caf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caf_project_details",
                        to="sws.caf",
                    ),
                ),
            ],
            options={
                "db_table": "caf_project_details",
            },
        ),
    ]
