# Generated by Django 5.1.5 on 2025-02-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0013_cafmanufacturingdetails_cafprojectdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentionIdGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "investment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("investment_id", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sws_intentions_generator",
            },
        ),
    ]
