# Generated by Django 5.1.5 on 2025-02-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0015_cafinvestmentdetails_delete_cafprojectdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerIntentionPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intention_id", models.CharField(max_length=50, unique=True)),
                (
                    "intention_doc",
                    models.FileField(
                        blank=True, null=True, upload_to="intention_pdfs/"
                    ),
                ),
                ("doc_url", models.URLField(blank=True, null=True)),
                (
                    "customer_project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_document",
                        to="sws.customerintentionproject",
                    ),
                ),
            ],
            options={
                "db_table": "sws_customer_intention_pdf",
            },
        ),
    ]
