# Generated by Django 5.1.5 on 2025-02-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0016_customerintentionpdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plot", models.CharField(max_length=255)),
                ("plot_size", models.IntegerField()),
                ("price", models.FloatField()),
                ("district", models.CharField(max_length=20)),
                ("industrial_area", models.CharField(max_length=100)),
                ("status", models.CharField()),
                ("latitude", models.CharField(max_length=20)),
                ("longitude", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "sws_plot_details",
            },
        ),
    ]
