# Generated by Django 5.1.5 on 2025-02-14 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0017_plotdetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWishList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sws.plotdetails",
                    ),
                ),
            ],
            options={
                "db_table": "sws_user_wish_list",
            },
        ),
    ]
