# Generated by Django 5.1.5 on 2025-02-15 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0018_userwishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plotdetails",
            name="district",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sws.district"
            ),
        ),
    ]
