# Generated by Django 5.1.5 on 2025-02-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0019_alter_plotdetails_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="CAFCreationPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caf_reference_id", models.CharField(max_length=50, unique=True)),
                (
                    "caf_doc",
                    models.FileField(blank=True, null=True, upload_to="caf_pdfs/"),
                ),
                ("pdf_url", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "caf",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caf_generated_pdfs",
                        to="sws.caf",
                    ),
                ),
            ],
            options={
                "db_table": "sws_caf_pdf",
            },
        ),
    ]
