# Generated by Django 5.1.5 on 2025-02-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0020_cafcreationpdf"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customerintentionproject",
            old_name="plant_machinery_cost",
            new_name="investment_in_pm",
        ),
        migrations.RemoveField(
            model_name="customerintentionproject",
            name="differently_abled",
        ),
        migrations.RemoveField(
            model_name="customerintentionproject",
            name="minority",
        ),
        migrations.RemoveField(
            model_name="customerintentionproject",
            name="pollution_category",
        ),
        migrations.RemoveField(
            model_name="customerintentionproject",
            name="project_name",
        ),
        migrations.RemoveField(
            model_name="customerintentionproject",
            name="total_investment_range",
        ),
        migrations.RemoveField(
            model_name="customerintentionproject",
            name="woman_entrepreneur",
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="company_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="district",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="investment_type",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="land_identified",
            field=models.CharField(default="", max_length=5),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="land_industrial_area",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="land_type",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="pincode",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="preffered_district",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="sub_sector",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="total_land_required",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
