# Generated by Django 5.1.5 on 2025-02-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sws",
            "0021_rename_plant_machinery_cost_customerintentionproject_investment_in_pm_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="caf",
            old_name="msme_registration_number",
            new_name="designation",
        ),
        migrations.RemoveField(
            model_name="caf",
            name="firm_email_id",
        ),
        migrations.RemoveField(
            model_name="caf",
            name="helpdesk_number",
        ),
        migrations.RemoveField(
            model_name="caf",
            name="organization_type",
        ),
        migrations.RemoveField(
            model_name="caf",
            name="registered_under_msme",
        ),
        migrations.RemoveField(
            model_name="caf",
            name="registration_date",
        ),
        migrations.AddField(
            model_name="caf",
            name="activity",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="caf",
            name="name_of_promoter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
