# Generated by Django 5.1.5 on 2025-02-18 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0022_rename_msme_registration_number_caf_designation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="city",
            new_name="state",
        ),
        migrations.RemoveField(
            model_name="commonapplication",
            name="date_of_birth",
        ),
    ]
