# Generated by Django 5.1.5 on 2025-02-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0023_rename_city_address_state_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cafinvestmentdetails",
            old_name="differently_abled",
            new_name="do_you_have_land",
        ),
        migrations.RenameField(
            model_name="cafinvestmentdetails",
            old_name="minority",
            new_name="export_oriented_unit",
        ),
        migrations.RenameField(
            model_name="cafinvestmentdetails",
            old_name="line_of_activity",
            new_name="land_address",
        ),
        migrations.RenameField(
            model_name="cafinvestmentdetails",
            old_name="building_value",
            new_name="land_district",
        ),
        migrations.RenameField(
            model_name="cafinvestmentdetails",
            old_name="district",
            new_name="land_registry_number",
        ),
        migrations.RenameField(
            model_name="cafinvestmentdetails",
            old_name="total_project_Value_words",
            new_name="product_name",
        ),
        migrations.RenameField(
            model_name="cafinvestmentdetails",
            old_name="plot_number",
            new_name="type_of_investment",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="building_height",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="land_value",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="pollution_category",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="tehsil",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="total_covered_area",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="total_open_area",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="total_project_Value",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="village",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="woman_entrepreneur",
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="dpr_document_path",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="export_percentage",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="land_pincode",
            field=models.CharField(default="", max_length=6),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="power_limit",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="project_category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="sub_sector",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="total_employee",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="total_investment",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="total_local_employee",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="type_of_land",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="water_limit",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="activity",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="direct_female_employee",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="direct_male_employee",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="indirect_female_employee",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="indirect_male_employee",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="industrial_area",
            field=models.CharField(default="", max_length=255),
        ),
    ]
