# Generated by Django 5.1.5 on 2025-02-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sws",
            "0024_rename_differently_abled_cafinvestmentdetails_do_you_have_land_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plotdetails",
            name="plot_size",
        ),
        migrations.RemoveField(
            model_name="plotdetails",
            name="price",
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="alloted_area",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="alloted_plot_no",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="booked_plot_no",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="booked_plots_area",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="industrial_area_type",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="not_for_plots_area",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="not_for_sale_plots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="regional_office",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="total_land_area",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="total_no_of_plots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="total_plot_area",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="vacant_plots",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="vacant_plots_area",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="plotdetails",
            name="industrial_area",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="plotdetails",
            name="latitude",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="plotdetails",
            name="longitude",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="plotdetails",
            name="plot",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="plotdetails",
            name="status",
            field=models.CharField(default="", max_length=20),
        ),
    ]
