# Generated by Django 5.1.5 on 2025-02-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0025_remove_plotdetails_plot_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerintentionproject",
            name="is_planned",
            field=models.CharField(default="", max_length=20),
        ),
    ]
