# Generated by Django 5.1.5 on 2025-02-20 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0026_customerintentionproject_is_planned"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "sws_subsector",
            },
        ),
    ]
