# Generated by Django 5.1.5 on 2025-02-20 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0027_subsector"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowYourPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyp_sector",
                        to="sws.sector",
                    ),
                ),
            ],
            options={
                "db_table": "sws_policies",
            },
        ),
        migrations.CreateModel(
            name="KnowYourPolicyContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "kwp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyp_content",
                        to="sws.knowyourpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "sws_policy_contents",
            },
        ),
    ]
