# Generated by Django 5.1.5 on 2025-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0028_knowyourpolicy_knowyourpolicycontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="industrialarealist",
            name="authority",
            field=models.CharField(default="", max_length=30),
        ),
    ]
