# Generated by Django 5.1.5 on 2025-02-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0029_industrialarealist_authority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerintentionproject",
            name="investment_type",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="land_industrial_area",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="land_type",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="sub_sector",
            field=models.CharField(default="", max_length=100),
        ),
    ]
