# Generated by Django 5.1.5 on 2025-03-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0030_alter_customerintentionproject_investment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerintentionproject",
            name="investment_in_pm",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="total_land_required",
            field=models.CharField(default="", max_length=100),
        ),
    ]
