# Generated by Django 5.1.5 on 2025-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0031_alter_customerintentionproject_investment_in_pm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerintentionproject",
            name="intention_type",
            field=models.CharField(
                choices=[("regular", "Regular"), ("incentive", "Incentive")],
                default="regular",
                max_length=10,
            ),
        ),
    ]
