# Generated by Django 5.1.5 on 2025-03-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0032_customerintentionproject_intention_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InvestmentRange",
        ),
        migrations.RemoveField(
            model_name="preoperational",
            name="user_profile",
        ),
        migrations.RemoveField(
            model_name="sitelocation",
            name="customer_project",
        ),
        migrations.DeleteModel(
            name="PreEstablishment",
        ),
        migrations.DeleteModel(
            name="PreOperational",
        ),
        migrations.DeleteModel(
            name="SiteLocation",
        ),
    ]
