# Generated by Django 5.1.5 on 2025-03-10 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0033_delete_investmentrange_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regionaloffice",
            name="district",
        ),
        migrations.CreateModel(
            name="RegionalOfficeDistrictMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.IntegerField(default=9999)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "In-Active"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rof_district",
                        to="sws.district",
                    ),
                ),
                (
                    "regional_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rof_regional_offices",
                        to="sws.regionaloffice",
                    ),
                ),
            ],
            options={
                "db_table": "sws_ro_district_mappings",
            },
        ),
    ]
