# Generated by Django 5.1.5 on 2025-03-10 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0034_remove_regionaloffice_district_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowyourpolicy",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="knowyourpolicy",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "In-Active"),
                    ("deleted", "Deleted"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="display_order",
            field=models.IntegerField(default=9999),
        ),
        migrations.AddField(
            model_name="sector",
            name="icon_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="knowyourpolicy",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.CreateModel(
            name="KnowYourPolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("document_link", models.TextField(default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "In-Active"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "kyp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyp_policy",
                        to="sws.knowyourpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "sws_policy_documents",
            },
        ),
        migrations.DeleteModel(
            name="KnowYourPolicyContent",
        ),
    ]
