# Generated by Django 5.1.5 on 2025-03-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0035_knowyourpolicy_content_knowyourpolicy_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plotdetails",
            name="extra_feature",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="ia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="industrial_areas",
                to="sws.industrialarealist",
            ),
        ),
        migrations.AddField(
            model_name="plotdetails",
            name="ro",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plot_regional_offices",
                to="sws.regionaloffice",
            ),
        ),
    ]
