# Generated by Django 5.1.5 on 2025-03-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0036_plotdetails_extra_feature_plotdetails_ia_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentlist",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name="CAFManufacturingDetails",
        ),
    ]
