# Generated by Django 5.1.5 on 2025-03-13 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0037_departmentlist_code_delete_cafmanufacturingdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowyourpolicy",
            name="policy_img",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="knowyourpolicy",
            name="policy_type",
            field=models.SmallIntegerField(
                default=2, help_text="1 for sector policy & 2 for other policies"
            ),
        ),
        migrations.AlterField(
            model_name="knowyourpolicy",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sws.sector",
            ),
        ),
    ]
