# Generated by Django 5.1.5 on 2025-03-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0038_knowyourpolicy_policy_img_knowyourpolicy_policy_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowyourpolicy",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
