# Generated by Django 5.1.5 on 2025-03-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0039_knowyourpolicy_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerintentionproject",
            name="activities",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.activity",
            ),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="districts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.district",
            ),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="land_ia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.industrialarealist",
            ),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="sectors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.sector",
            ),
        ),
        migrations.AddField(
            model_name="customerintentionproject",
            name="subsectors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.subsector",
            ),
        ),
        migrations.AddField(
            model_name="subsector",
            name="display_order",
            field=models.IntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="district",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="land_industrial_area",
            field=models.CharField(default="", max_length=200),
        ),
    ]
