# Generated by Django 5.1.5 on 2025-03-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0040_customerintentionproject_activities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caf",
            name="activity",
        ),
    ]
