# Generated by Django 5.1.5 on 2025-03-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0041_remove_caf_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerintentionproject",
            name="is_planned",
        ),
        migrations.AddField(
            model_name="address",
            name="districts",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.district",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="states",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.state",
            ),
        ),
        migrations.AddField(
            model_name="caf",
            name="desig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.designation",
            ),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="acknowledge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="acknowledge_time",
            field=models.CharField(blank=True, default="", max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="activities",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.activity",
            ),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.district",
            ),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="land_ia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.industrialarealist",
            ),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="preffered_districts",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="sectors",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.sector",
            ),
        ),
        migrations.AddField(
            model_name="cafinvestmentdetails",
            name="subsector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.subsector",
            ),
        ),
        migrations.AddField(
            model_name="commonapplication",
            name="desig",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.designation",
            ),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="dpr_document_path",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="industrial_area",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="land_address",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="land_district",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="land_pincode",
            field=models.CharField(blank=True, default="", max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="land_registry_number",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="type_of_land",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
