# Generated by Django 5.1.5 on 2025-03-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0042_remove_customerintentionproject_is_planned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerintentionproject",
            name="product_proposed_date",
            field=models.CharField(default="NA", max_length=50),
        ),
    ]
