# Generated by Django 5.1.5 on 2025-03-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0043_alter_customerintentionproject_product_proposed_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commonapplication",
            name="aadhaar_number",
        ),
    ]
