# Generated by Django 5.1.5 on 2025-03-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0044_remove_commonapplication_aadhaar_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lineofactivity",
            name="business_industry",
        ),
        migrations.RemoveField(
            model_name="otherservicemapping",
            name="service",
        ),
        migrations.RemoveField(
            model_name="productpollutionmapping",
            name="pollution_type",
        ),
        migrations.RemoveField(
            model_name="productpollutionmapping",
            name="product",
        ),
        migrations.RemoveField(
            model_name="sectorservicelist",
            name="sector",
        ),
        migrations.RemoveField(
            model_name="sectorservicelist",
            name="service",
        ),
        migrations.RemoveField(
            model_name="servicelist",
            name="department",
        ),
        migrations.RemoveField(
            model_name="userwishlist",
            name="plot",
        ),
        migrations.RemoveField(
            model_name="caf",
            name="desig",
        ),
        migrations.RemoveField(
            model_name="caf",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="caf",
            name="name_of_promoter",
        ),
        migrations.RemoveField(
            model_name="caf",
            name="website_url",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="direct_female_employee",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="direct_male_employee",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="dpr_document_path",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="indirect_female_employee",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="indirect_male_employee",
        ),
        migrations.RemoveField(
            model_name="cafinvestmentdetails",
            name="project_category",
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="export_percentage",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="product_proposed_date",
            field=models.CharField(default="NA", max_length=50),
        ),
        migrations.DeleteModel(
            name="BusinessIndustry",
        ),
        migrations.DeleteModel(
            name="LineOfActivity",
        ),
        migrations.DeleteModel(
            name="OtherServiceMapping",
        ),
        migrations.DeleteModel(
            name="ProductPollutionMapping",
        ),
        migrations.DeleteModel(
            name="SectorServiceList",
        ),
        migrations.DeleteModel(
            name="ServiceList",
        ),
        migrations.DeleteModel(
            name="UserWishList",
        ),
    ]
