# Generated by Django 5.1.5 on 2025-04-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0045_remove_lineofactivity_business_industry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictBlockList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="district_blocks",
                        to="sws.district",
                    ),
                ),
            ],
            options={
                "db_table": "sws_district_blocks",
            },
        ),
        migrations.CreateModel(
            name="LineOfActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        default="active",
                        help_text="active, inactive or deleted",
                        max_length=10,
                    ),
                ),
                (
                    "sectors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sws.sector"
                    ),
                ),
            ],
            options={
                "db_table": "sws_line_of_activities",
            },
        ),
    ]
