# Generated by Django 5.1.5 on 2025-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0046_districtblocklist_lineofactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementUnitList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        default="active",
                        help_text="active, inactive or deleted",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "sws_measurements_units",
            },
        ),
    ]
