# Generated by Django 5.1.5 on 2025-04-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incentive", "0019_remove_incafproject_line_of_activity_and_more"),
        ("sws", "0047_measurementunitlist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LineOfActivity",
        ),
    ]
