# Generated by Django 5.1.5 on 2025-04-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0048_delete_lineofactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="nic_code",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="subsector",
            name="nic_code",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="sector",
            name="name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="subsector",
            name="name",
            field=models.TextField(),
        ),
    ]
