# Generated by Django 5.1.5 on 2025-04-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0049_sector_nic_code_subsector_nic_code_alter_sector_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonapplication",
            name="country_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="commonapplication",
            name="country_code_value",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
