# Generated by Django 5.1.5 on 2025-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0050_commonapplication_country_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="industrialarealist",
            name="airport_distance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="busstand_distance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="city_distance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="develop_status",
            field=models.CharField(default="Developed", max_length=30),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="drainage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="electricity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="nearest_airport",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="nearest_busstand",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="nearest_city",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="nearest_railway",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="other_amenities",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="railway_distance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="road",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="water",
            field=models.BooleanField(default=False),
        ),
    ]
