# Generated by Django 5.1.5 on 2025-04-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0051_industrialarealist_airport_distance_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="industrialarealist",
            old_name="nearest_busstand",
            new_name="nearest_port",
        ),
        migrations.RemoveField(
            model_name="industrialarealist",
            name="airport_distance",
        ),
        migrations.RemoveField(
            model_name="industrialarealist",
            name="busstand_distance",
        ),
        migrations.RemoveField(
            model_name="industrialarealist",
            name="city_distance",
        ),
        migrations.RemoveField(
            model_name="industrialarealist",
            name="drainage",
        ),
        migrations.RemoveField(
            model_name="industrialarealist",
            name="other_amenities",
        ),
        migrations.RemoveField(
            model_name="industrialarealist",
            name="railway_distance",
        ),
        migrations.AddField(
            model_name="industrialarealist",
            name="nearest_road",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
