# Generated by Django 5.1.5 on 2025-05-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sws",
            "0052_rename_nearest_busstand_industrialarealist_nearest_port_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="incentive_method",
            field=models.CharField(default="get_general_incentive", max_length=100),
        ),
        migrations.AddField(
            model_name="sector",
            name="sector_multiple",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="sector",
            name="show_in_incentive_calc",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sector",
            name="show_in_kya",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subsector",
            name="show_in_kya",
            field=models.BooleanField(default=False),
        ),
    ]
