# Generated by Django 5.1.5 on 2025-05-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0053_sector_incentive_method_sector_sector_multiple_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerintentionproject",
            name="power_required",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="water_required",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
