# Generated by Django 5.1.5 on 2025-05-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0054_alter_customerintentionproject_power_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafcreationpdf",
            name="caf_doc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cafcreationpdf",
            name="caf_reference_id",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="cafcreationpdf",
            name="pdf_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
