# Generated by Django 5.1.5 on 2025-05-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0056_alter_customerintentionproject_activity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafinvestmentdetails",
            name="sub_sector",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customerintentionproject",
            name="sub_sector",
            field=models.TextField(blank=True, null=True),
        ),
    ]
