# Generated by Django 5.1.5 on 2025-05-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0057_alter_cafinvestmentdetails_sub_sector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerintentionproject",
            name="product_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
