# Generated by Django 5.1.5 on 2025-06-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0058_alter_customerintentionproject_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="incentive_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
