# Generated by Django 5.1.5 on 2025-06-25 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0059_sector_incentive_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerHelpdesk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=100)),
                ("mobile_no", models.CharField(max_length=13)),
                ("message", models.TextField()),
                ("acknowledgement", models.BooleanField(default=False)),
                ("status", models.CharField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sws_customer_helpdesk",
            },
        ),
        migrations.CreateModel(
            name="CustomerSubscriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sws_customer_subscriptions",
            },
        ),
    ]
