# Generated by Django 5.1.5 on 2025-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0060_customerhelpdesk_customersubscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customersubscriptions",
            name="email",
            field=models.EmailField(max_length=100),
        ),
    ]
