# Generated by Django 5.1.5 on 2025-07-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0061_alter_customersubscriptions_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafcreationpdf",
            name="is_document_sign",
            field=models.BooleanField(default=False),
        ),
    ]
