# Generated by Django 5.1.5 on 2025-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0062_cafcreationpdf_is_document_sign"),
    ]

    operations = [
        migrations.AddField(
            model_name="districtblocklist",
            name="block_priority",
            field=models.CharField(
                default="Non Priority",
                help_text="Priority or Non Priority",
                max_length=20,
            ),
        ),
    ]
