# Generated by Django 5.1.5 on 2025-08-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0063_districtblocklist_block_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="industrialarealist",
            name="incentive_authority",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
