# Generated by Django 5.1.5 on 2025-08-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0064_industrialarealist_incentive_authority"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerintentionproject",
            name="intention_file_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
