# Generated by Django 5.1.5 on 2025-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0065_customerintentionproject_intention_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="commonapplication",
            name="other_designation",
            field=models.CharField(
                blank=True, help_text="Other designation", max_length=50, null=True
            ),
        ),
    ]
