# Generated by Django 5.1.5 on 2025-08-20 06:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0066_commonapplication_other_designation"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackFormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "mobile_no",
                    models.CharField(
                        blank=True, default=None, max_length=13, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("address", models.TextField(blank=True, default="", null=True)),
                (
                    "state_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "district_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("document_link", models.TextField(blank=True, default="", null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sws.district",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sws.state",
                    ),
                ),
            ],
            options={
                "db_table": "sws_feedback_form",
            },
        ),
    ]
