# Generated by Django 5.1.5 on 2025-08-22 06:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0016_approvalconfigurationmodel"),
        ("sws", "0067_feedbackformmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceConfigModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_service_config",
                        to="approval.approvallist",
                    ),
                ),
                (
                    "deparment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deparment_service_config",
                        to="sws.departmentlist",
                    ),
                ),
            ],
            options={
                "db_table": "sws_service_config",
            },
        ),
        migrations.CreateModel(
            name="ServiceDynamicFieldModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_tag", models.CharField(blank=True, max_length=255, null=True)),
                ("field_title", models.TextField(blank=True, null=True)),
                ("field_type", models.CharField(blank=True, max_length=20, null=True)),
                ("field_value", models.JSONField(blank=True, null=True)),
                ("field_status", models.BooleanField(default=True)),
                ("field_order", models.IntegerField(default=999)),
                (
                    "sevice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_service_charge",
                        to="sws.serviceconfigmodel",
                    ),
                ),
            ],
            options={
                "db_table": "sws_service_dynamic_fields",
            },
        ),
    ]
