# Generated by Django 5.1.5 on 2025-08-22 08:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval", "0017_usercafservice_department_and_more"),
        ("sws", "0068_serviceconfigmodel_servicedynamicfieldmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDepartmentAPILogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deparment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deparment_api_log",
                        to="approval.usercafservice",
                    ),
                ),
            ],
            options={
                "db_table": "sws_service_api_logs",
            },
        ),
        migrations.CreateModel(
            name="ServiceDepartmentAPIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deparment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deparment_api",
                        to="sws.departmentlist",
                    ),
                ),
            ],
            options={
                "db_table": "sws_service_api",
            },
        ),
    ]
