# Generated by Django 5.1.5 on 2025-08-22 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sws", "0069_servicedepartmentapilogmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequestNumberModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_request_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "caf",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sws.caf",
                    ),
                ),
            ],
            options={
                "db_table": "sws_service_request_number",
            },
        ),
    ]
