# Generated by Django 5.1.5 on 2025-01-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="email",
            new_name="email_id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="mobile",
            new_name="mobile_no",
        ),
    ]
