# Generated by Django 5.1.5 on 2025-01-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_email_user_email_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="user_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("mobile_no", models.CharField(max_length=15, unique=True)),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="user",
        ),
    ]
