# Generated by Django 5.1.5 on 2025-01-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_profile_delete_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user_profile",
            new_name="user",
        ),
    ]
