# Generated by Django 5.1.5 on 2025-01-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_rename_user_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
