# Generated by Django 5.1.5 on 2025-01-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_user_mobile_no"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user",
            new_name="CustomUserProfile",
        ),
    ]
