# Generated by Django 5.1.5 on 2025-02-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_customuserprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuserprofile",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
