# Generated by Django 5.1.5 on 2025-02-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuserprofile_otp_customuserprofile_otp_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuserprofile",
            name="mobile_no",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
