# Generated by Django 5.1.5 on 2025-02-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_alter_customuserprofile_mobile_no"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuserprofile",
            table="customer",
        ),
    ]
