# Generated by Django 5.1.5 on 2025-02-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_alter_customuserprofile_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuserprofile",
            name="email_id",
        ),
        migrations.RemoveField(
            model_name="customuserprofile",
            name="password",
        ),
    ]
