# Generated by Django 5.1.5 on 2025-02-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_remove_customuserprofile_email_id_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuserprofile",
            table="user_profile",
        ),
    ]
