# Generated by Django 5.1.5 on 2025-02-16 15:03

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_customuserprofile_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuserprofile",
            name="company_name",
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="aadhar_number",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="dob",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="mode_of_registration",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("guest", "Guest"),
                    ("offline", "Offline"),
                ],
                default="online",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("block", "Block"),
                    ("inactive", "In-Active"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("regular", "Regular"),
                    ("guest", "Guest"),
                ],
                default="regular",
                max_length=10,
            ),
        ),
    ]
