# Generated by Django 5.1.5 on 2025-02-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_remove_customuserprofile_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuserprofile",
            name="alternate_email_id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
