# Generated by Django 5.1.5 on 2025-02-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_userprofilestatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuserprofile",
            name="dob",
        ),
    ]
