# Generated by Django 5.1.5 on 2025-02-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_remove_customuserprofile_dob"),
        ("sws", "0019_alter_plotdetails_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuserprofile",
            name="designation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sws.designation",
            ),
        ),
    ]
