# Generated by Django 5.1.5 on 2025-03-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0020_permission_role_rolehaspermission_userhaspermission_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuserprofile",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="customuserprofile",
            name="mobile_no",
            field=models.CharField(
                blank=True, default=None, max_length=13, null=True, unique=True
            ),
        ),
    ]
