# Generated by Django 5.1.5 on 2025-03-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0022_alter_customuserprofile_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuserprofile",
            name="aadhar_number",
        ),
    ]
