# Generated by Django 5.1.5 on 2025-04-10 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0024_module_modulehaspemission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rolehaspermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="rolehaspermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="rolehaspermission",
            name="role",
        ),
        migrations.AlterUniqueTogether(
            name="userhaspermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userhaspermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="userhaspermission",
            name="user",
        ),
        migrations.RenameField(
            model_name="permission",
            old_name="permission_tag",
            new_name="name",
        ),
        migrations.AlterModelTable(
            name="module",
            table="project_modules",
        ),
        migrations.AlterModelTable(
            name="permission",
            table="project_permissions",
        ),
        migrations.AlterModelTable(
            name="role",
            table="project_roles",
        ),
        migrations.AlterModelTable(
            name="userhasrole",
            table="project_user_has_roles",
        ),
        migrations.CreateModel(
            name="ModuleHasPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.module",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.permission",
                    ),
                ),
            ],
            options={
                "db_table": "project_module_permissions",
                "unique_together": {("module", "permission")},
            },
        ),
        migrations.CreateModel(
            name="RoleModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.module",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.role",
                    ),
                ),
            ],
            options={
                "db_table": "project_role_module_permissions",
                "unique_together": {("role", "module", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserModulePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.module",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_user_module_permissions",
                "unique_together": {("user", "module", "permission")},
            },
        ),
        migrations.DeleteModel(
            name="ModuleHasPemission",
        ),
        migrations.DeleteModel(
            name="RoleHasPermission",
        ),
        migrations.DeleteModel(
            name="UserHasPermission",
        ),
    ]
