# Generated by Django 5.1.5 on 2025-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0025_alter_rolehaspermission_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhasrole",
            name="role_type",
            field=models.CharField(
                default="primary", help_text="primary, secondary", max_length=20
            ),
        ),
        migrations.DeleteModel(
            name="ModuleHasPermission",
        ),
    ]
