# Generated by Django 5.1.5 on 2025-04-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_userhasrole_role_type_delete_modulehaspermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flow_type",
                    models.CharField(help_text="claim, incentive etc", max_length=20),
                ),
                ("level_no", models.SmallIntegerField()),
                (
                    "next_flow_type",
                    models.CharField(
                        blank=True,
                        help_text="claim, incentive etc",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "current_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wf_current_role",
                        to="authentication.role",
                    ),
                ),
                (
                    "next_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wf_next_role",
                        to="authentication.role",
                    ),
                ),
            ],
            options={
                "db_table": "project_workflow",
            },
        ),
    ]
