# Generated by Django 5.1.5 on 2025-04-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0027_workflowlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowlist",
            name="next_flow_type",
        ),
        migrations.RemoveField(
            model_name="workflowlist",
            name="next_role",
        ),
        migrations.AddField(
            model_name="workflowlist",
            name="current_status",
            field=models.CharField(
                blank=True,
                help_text="Pending from Manager action etc",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflowlist",
            name="sla_period",
            field=models.IntegerField(blank=True, help_text="SLA Period", null=True),
        ),
        migrations.CreateModel(
            name="WorkflowItemList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "next_flow_type",
                    models.CharField(
                        blank=True,
                        help_text="claim, incentive etc",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        blank=True,
                        help_text="Forward to next level",
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        help_text="Pending from GM action etc",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "next_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wf_next_role",
                        to="authentication.role",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.workflowlist",
                    ),
                ),
            ],
            options={
                "db_table": "project_workflow_items",
            },
        ),
    ]
