# Generated by Django 5.1.5 on 2025-04-19 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_remove_workflowlist_next_flow_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("iso", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "tbl_countries",
            },
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="document_folder",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="country_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.country",
            ),
        ),
    ]
