# Generated by Django 5.1.5 on 2025-04-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0029_country_customuserprofile_document_folder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuserprofile",
            name="document_folder",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
