# Generated by Django 5.1.5 on 2025-05-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0030_alter_customuserprofile_document_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuserprofile",
            name="dob",
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="father_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="pan_card_number",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="pan_verify",
            field=models.BooleanField(default=False),
        ),
    ]
