# Generated by Django 5.1.5 on 2025-06-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0031_customuserprofile_dob_customuserprofile_father_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuserprofile",
            name="email_verify",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuserprofile",
            name="wrong_otp_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
