# Generated by Django 5.1.5 on 2025-08-18 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0032_customuserprofile_email_verify_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebAppointmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "designation_name",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "mobile_no",
                    models.CharField(
                        blank=True, default=None, max_length=13, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                (
                    "appointment_with",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("date_of_appointment", models.DateField(blank=True, null=True)),
                (
                    "meeting_reason",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("status", models.CharField(default="New", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "web_appointment_form",
            },
        ),
    ]
