# Generated by Django 5.1.5 on 2025-04-11 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_center", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("file_name", models.CharField(blank=True, max_length=100, null=True)),
                ("file_type", models.CharField(blank=True, max_length=100, null=True)),
                ("minio_path", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "document_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_source",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "application_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "entity_document_center",
            },
        ),
    ]
