# Generated by Django 5.1.5 on 2025-04-19 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document_center", "0002_documentcenter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DocumentCenter",
            new_name="EntityDocumentCenter",
        ),
    ]
