# Generated by Django 5.1.5 on 2025-04-19 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_center", "0003_rename_documentcenter_entitydocumentcenter"),
        ("incentive", "0018_remove_documentlist_gstin_doc_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "document_events",
            },
        ),
        migrations.CreateModel(
            name="DocumentEventBased",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incentive.documentlist",
                    ),
                ),
                (
                    "form_purpose",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="document_center.documentevent",
                    ),
                ),
            ],
            options={
                "db_table": "document_based_on_event",
            },
        ),
        migrations.CreateModel(
            name="UserDocumentCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="digilocker, entity, manual",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=100, null=True)),
                ("file_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "entity_doc_type",
                    models.CharField(
                        blank=True, help_text="Document Type", max_length=50, null=True
                    ),
                ),
                (
                    "digi_doc_type",
                    models.CharField(
                        blank=True, help_text="Digi doc Type", max_length=50, null=True
                    ),
                ),
                ("minio_path", models.TextField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incentive.documentlist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_center",
            },
        ),
    ]
