# Generated by Django 5.1.5 on 2025-04-19 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_center", "0004_documentevent_documenteventbased_userdocumentcenter"),
        ("incentive", "0018_remove_documentlist_gstin_doc_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenteventbased",
            name="form_purpose",
        ),
        migrations.AddField(
            model_name="documenteventbased",
            name="event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doc_events",
                to="document_center.documentevent",
            ),
        ),
        migrations.AlterField(
            model_name="documenteventbased",
            name="document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_docs",
                to="incentive.documentlist",
            ),
        ),
    ]
