# Generated by Django 5.1.5 on 2025-05-02 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document_center", "0005_remove_documenteventbased_form_purpose_and_more"),
        ("incentive", "0024_remove_incentiveagendaproduct_caf_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionControlTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_url", models.CharField(max_length=255)),
                ("doc_name", models.CharField(blank=True, max_length=50, null=True)),
                ("module_name", models.CharField(blank=True, max_length=50, null=True)),
                ("version_no", models.SmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doc_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incentive.documentlist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "version_control_tracker",
            },
        ),
    ]
